Repository Avaiga/taipy-doc, pull requests merged in 2022-12, with the labels that each got.

#279 Private repositories must be potentially ignored in local & develop modes.
  INSTALLATION.md
  Pipfile
  tools/README.md
  tools/fetch_source_files.py
  tools/fetch_source_files.sh
Labels: 🟥 Priority: Critical, 💥Malfunction

#288 fix(css): fix issue with content horizontal overfllow with too long code lines
  tools/assets/stylesheets/avaiga.css
Labels: 📄 Documentation, 💥Malfunction

#291 Release / feat(css): align quick access card title and icon
  docs/index.md
  tools/assets/stylesheets/avaiga.css
Labels: 📄 Documentation

#296 Fix/ Wrong SQL engine support on taipy 2.0
  docs/manuals/core/config/data-node-config.md
Labels: 💥Malfunction

#312 doc: add api changes on taipy-config
  docs/manuals/core/config/advanced-config.md
Labels: 📈 Improvement, 📄 Documentation, ⚙️Configuration
