Repository Avaiga/taipy-doc, pull requests merged in 2022-07, with the labels that each got.

#164 Add the Enterprise features documentation to the global doc set
  Pipfile
  docs/manuals/auth/authentication.md
  docs/manuals/auth/authorization.md
  docs/manuals/auth/index.md
  docs/manuals/deployment/docker/airflow.md
  docs/manuals/gui/binding.md
  docs/manuals/gui/pages.md
  docs/manuals/gui/viselements/index.md
  docs/manuals/reference.md
  mkdocs.yml_template
  tools/fetch_source_files.sh
  tools/setup_generation.py
Labels: documentation

#165 Creating Doc Set 1.1
  mkdocs.yml_template
Labels: devops, documentation

#166 Git clone from ReadTheDocs
  tools/fetch_source_files.sh
Labels: devops, documentation

#171 Reference new taipy-config package.
  tools/fetch_source_files.sh
  tools/setup_generation.py
Labels: documentation, Refactoring

#170 Added doc for accessing dn directly from scenario and pipeline
  docs/manuals/core/entities/data-node-mgt.md
  docs/relnotes.md
Labels: back-end

#187 Generate and integrate the REST API in the Reference Manual
  .gitignore
  docs/manuals/auth/authorization.md
  docs/manuals/reference_rest/index.md
  mkdocs.yml_template
  tools/fetch_source_files.sh
  tools/generate_rest.py
  tools/postprocess.py
  tools/setup_generation.py
Labels: documentation
