Repository Avaiga/taipy-doc, pull requests merged in 2022-10, with the labels that each got.

#219 RefMan generation fixes (#203, #212)
  docs/manuals/gui/callbacks.md
  docs/manuals/gui/configuration.md
  docs/manuals/gui/extension.md
  docs/manuals/gui/extension_assets.md
  docs/manuals/gui/extension_data.md
  docs/manuals/gui/extension_dynamic_element.md
  docs/manuals/gui/extension_list_of_values.md
  docs/manuals/gui/extension_packaging.md
  docs/manuals/gui/extension_static_element.md
  docs/manuals/gui/images/extension-static1-d.png
  docs/manuals/gui/images/extension-static1-l.png
  docs/manuals/gui/images/extension-static2-d.png
  docs/manuals/gui/images/extension-static2-l.png
  docs/manuals/gui/images/extension-static3-d.png
  docs/manuals/gui/images/extension-static3-l.png
  docs/manuals/gui/pages.md
  mkdocs.yml_template
  tools/postprocess.py
  tools/setup_generation.py
Labels: devops, documentation

#226 Update Release Notes for 2.0.0
  CONTRIBUTING.md
  docs/relnotes.md
Labels: documentation

#227 Added notes for 1.1.3
  docs/relnotes.md
Labels: documentation

#232 Heroku deployment settings doc in incomplete (#229)
  docs/manuals/deployment/heroku/git.md
  tools/fetch_source_files.sh
Labels: devops, documentation

#238 Revise contributing doc's text
  CONTRIBUTING.md
  docs/contributing/contributing.md
Labels: documentation

#237 Split setup_generation file into multiple files
  tools/README.md
  tools/setup_generation.py
  tools/setup_generation/__init__.py
  tools/setup_generation/setup.py
  tools/setup_generation/step_getting_started.py
  tools/setup_generation/step_gui_ext_refman.py
  tools/setup_generation/step_refman.py
  tools/setup_generation/step_rest_refman.py
  tools/setup_generation/step_viselements.py
Labels: devops, documentation

#243 Inject into config.py the methods to document in RefMan
  tools/setup_generation/step_refman.py
Labels: documentation

#241 feature/ added doc for expose parent entities
  docs/manuals/core/entities/data-node-mgt.md
  docs/manuals/core/entities/pipeline-mgt.md
  docs/manuals/core/entities/task-mgt.md
  docs/relnotes.md
Labels: documentation

#242 feature/ added doc for new cache behavior
  docs/manuals/core/entities/data-node-mgt.md
  docs/relnotes.md
Labels: documentation

#251 New home page design
  docs/images/icons/dashboard-w.svg
  docs/images/icons/dashboard.svg
  docs/images/icons/flag-w.svg
  docs/images/icons/flag.svg
  docs/images/icons/menu_book-w.svg
  docs/images/icons/menu_book.svg
  docs/images/icons/tune-w.svg
  docs/images/icons/tune.svg
  docs/images/taipy-structure-vector.svg
  docs/index.md
  docs/manuals/gui/viselements/menu-d.png
  docs/manuals/gui/viselements/menu-dh.png
  docs/manuals/gui/viselements/menu-l.png
  docs/manuals/gui/viselements/menu-lh.png
  docs/manuals/gui/viselements/selector-d.png
  docs/manuals/gui/viselements/selector-dh.png
  docs/manuals/gui/viselements/selector-l.png
  docs/manuals/gui/viselements/selector-lh.png
  tools/assets/stylesheets/avaiga.css
  tools/assets/stylesheets/partials/_grid.css
Labels: documentation

#253 Update Release Notes for taipy-gui 2.0.2 (#252)
  docs/relnotes.md
Labels: enhancement, documentation

#256 Rely on the new format for GUI elements documentation (#247)
  docs/contributing/contributing.md
  docs/relnotes.md
  tools/setup_generation.py
  tools/setup_generation/__init__.py
  tools/setup_generation/setup.py
  tools/setup_generation/step_getting_started.py
  tools/setup_generation/step_refman.py
  tools/setup_generation/step_rest_refman.py
  tools/setup_generation/step_viselements.py
Labels: devops, documentation
