Repository Avaiga/taipy-doc, pull requests merged in 2022-11, with the labels that each got.

#262 Doc/from vincent
  .gitignore
  docs/manuals/core/concepts/execution-flow.md
  docs/manuals/core/config/data-node-config.md
  docs/manuals/core/config/scenario-config.md
  docs/manuals/core/entities/data-node-mgt.md
  docs/manuals/core/entities/scheduling-and-job-execution.md
  docs/manuals/running_services/index.md
  tools/setup_generation/step_refman.py
Labels: bug

#266 doc(index): replace old taipy logo in image control tooltip
  docs/manuals/gui/viselements/image-d.png
  docs/manuals/gui/viselements/image-dh.png
  docs/manuals/gui/viselements/image-l.png
  docs/manuals/gui/viselements/image-lh.png
Labels: documentation

#263 Rewrite fetch source files (#249)
  .gitignore
  docs/contributing/contributing.md
  docs/manuals/gui/callbacks.md
  docs/manuals/gui/viselements/index.md
  tools/fetch_source_files.py
  tools/setup_generation.py
  tools/setup_generation/__init__.py
  tools/setup_generation/setup.py
  tools/setup_generation/step_refman.py
Labels: devops, documentation

#268 Fix Back button issue on home page
  .readthedocs.yaml
  INSTALLATION.md
  docs/index.md
  mkdocs.yml_template
  tools/_setup_generation/__init__.py
  tools/_setup_generation/setup.py
  tools/_setup_generation/step_getting_started.py
  tools/_setup_generation/step_gui_ext_refman.py
  tools/_setup_generation/step_refman.py
  tools/_setup_generation/step_rest_refman.py
  tools/_setup_generation/step_viselements.py
  tools/setup_generation.py
Labels: devops, documentation

#269 Generate taipy-doc's pipfile based on the other repositories' (#202)
  Pipfile
  mkdocs.yml_template
  tools/fetch_source_files.py
Labels: devops
