Repository Avaiga/taipy-doc, pull requests merged in 2022-05, with the labels that each got.

#122 Concurrent deployed doc
  .readthedocs.yaml
  Pipfile
  mkdocs.yml_template
  tools/fetch_source_files.sh
  tools/postprocess.py
  tools/setup_generation.py
Labels: documentation

#127 Stop using GH-pages
  .github/workflows/doc.yml
Labels: documentation

#132 New logos & fix links to doc site
  docs/authors.md
  docs/credits/development_lead.md
  docs/manuals/deployment/linux/redhat.md
  mkdocs.yml_template
  tools/assets/images/favicon.png
  tools/assets/images/taipy-logo.png
  tools/fetch_source_files.sh
  tools/postprocess.py
  tools/setup_generation.py
Labels: enhancement, documentation

#134 Update Airflow config default
  docs/manuals/core/config/job-config.md
  docs/manuals/deployment/docker/docker-compose.yml.md
Labels: documentation

#129 Replace edition with edit
  docs/manuals/core/entities/data-node-mgt.md
  docs/manuals/rest/endpoints.md
Labels: documentation

#136 Tiny typo fixed
  docs/index.md
  docs/manuals/about.md
  docs/manuals/deployment/linux/redhat.md
  docs/manuals/deployment/linux/ubuntu.md
Labels: enhancement, documentation

#135 Update history and site versioning
  docs/history.md
  docs/manuals/deployment/linux/redhat.md
  mkdocs.yml_template
  tools/fetch_source_files.sh
  tools/postprocess.py
  tools/setup_generation.py
Labels: documentation

#137 Integrate changes done in 1.0
  docs/authors.md
  docs/credits/development_lead.md
  docs/index.md
  docs/manuals/about.md
  docs/manuals/deployment/linux/redhat.md
  docs/manuals/deployment/linux/ubuntu.md
  mkdocs.yml_template
  tools/assets/images/favicon.png
  tools/assets/images/taipy-logo.png
  tools/fetch_source_files.sh
  tools/postprocess.py
  tools/setup_generation.py
Labels: enhancement, documentation

#140 Replace Ubuntu by RHEL
  docs/manuals/deployment/linux/redhat.md
Labels: documentation

#141 Bubble chart with Colors
  docs/manuals/gui/viselements/charts/scatter.md
  docs/manuals/gui/viselements/charts/scatter4.png
Labels: enhancement, Front-End, documentation

#139 Replace Ubuntu by RHEL
  docs/manuals/deployment/linux/redhat.md
Labels: documentation

#144 Mainly expose Taipy Core features from the taipy.core package
  Pipfile
  docs/credits/development_lead.md
  docs/manuals/gui/viselements/charts/scatter.md
  tools/assets/stylesheets/avaiga.css
  tools/fetch_source_files.sh
  tools/setup_generation.py
Labels: back-end, enhancement, Front-End, documentation, Rest
