Repository Avaiga/taipy-doc, pull requests merged in 2022-04, with the labels that each got.

#95 Gui UserMan update (Part 3)
  docs/images/taipy-structure.svg
  docs/index.md
  docs/manuals/gui/viselements/charts/bar.md
  docs/manuals/gui/viselements/charts/basics.md
  docs/manuals/gui/viselements/charts/basics1.png
  docs/manuals/gui/viselements/charts/basics2.png
  docs/manuals/gui/viselements/charts/basics3.png
  docs/manuals/gui/viselements/charts/basics4.png
  docs/manuals/gui/viselements/charts/basics5-1.png
  docs/manuals/gui/viselements/charts/basics5-2.png
  docs/manuals/gui/viselements/charts/basics6.png
  docs/manuals/gui/viselements/charts/line.md
  docs/manuals/gui/viselements/charts/others.md
  docs/manuals/gui/viselements/charts/scatter.md
Labels: documentation

#96 Custom domain
  CNAME
Labels: devops

#88 Fix Getting started bad link + update Getting Started navbar based on summary
  .github/workflows/doc.yml
  .gitignore
  tools/fetch_source_files.sh
  tools/setup_generation.py
Labels: documentation

#106 Extract getting started steps from ReadMe
  .github/workflows/doc.yml
  tools/fetch_source_files.sh
  tools/setup_generation.py
Labels: documentation

#107 Gui UserMan update (Part 5)
  docs/manuals/gui/viselements/charts/Corel Auto-Preserve/bar4.png
  docs/manuals/gui/viselements/charts/bar.md
  docs/manuals/gui/viselements/charts/bar4.png
  docs/manuals/gui/viselements/charts/bar5.png
  docs/manuals/gui/viselements/charts/bar6.png
  docs/manuals/gui/viselements/charts/others.md
  docs/manuals/gui/viselements/charts/others1.png
  tools/postprocess.py
Labels: Front-End, documentation

#108 Gui UserMan update (Part 6)
  .github/workflows/doc.yml
  docs/manuals/gui/viselements/charts/line.md
  docs/manuals/gui/viselements/charts/scatter.md
  docs/manuals/gui/viselements/charts/scatter1.png
  docs/manuals/gui/viselements/charts/scatter2.png
  docs/manuals/gui/viselements/charts/scatter3.png
  tools/fetch_source_files.sh
Labels: Front-End, documentation

#109 Gui UserMan update (Part 7)
  docs/manuals/gui/viselements/charts/scatter.md
  tools/assets/stylesheets/avaiga.css
Labels: documentation

#113 Properly handle Mandatory visual elements' mandatory properties.
  docs/manuals/gui/pages.md
  tools/setup_generation.py
Labels: enhancement, Front-End, documentation

#120 Allow different module versions for doc generation.
  tools/fetch_source_files.sh
Labels: devops, documentation
