Repository Avaiga/taipy-doc, pull requests merged in 2022-06, with the labels that each got.

#150 Feature - Rename "path" to "default_path"
  .pre-commit-config.yaml
  docs/manuals/core/config.toml
  docs/manuals/core/config/advanced-config.md
  docs/manuals/core/config/data-node-config.md
  docs/manuals/core/entities/scenario-creation.md
  docs/manuals/core/my_config.py
Labels: documentation

#153 Initialize Release Notes for 1.1
  docs/history.md
  docs/manuals/gui/binding.md
  docs/manuals/gui/viselements/charts/others-maps1.png
  docs/manuals/gui/viselements/charts/others.md
  docs/manuals/reference.md
  docs/relnotes.md
  mkdocs.yml_template
  tools/setup_generation.py
Labels: enhancement, documentation

#155 Fix version of mkdocstrings
  Pipfile
Labels: documentation

#156 Doc/#149 update doc deployment
  docs/manuals/deployment/heroku/docker.md
  docs/manuals/deployment/heroku/getting-started.md
  docs/manuals/deployment/heroku/git.md
  docs/manuals/deployment/heroku/prepare-taipy-for-deployment.md
  docs/manuals/deployment/prepare-taipy-for-deployment.md
  docs/manuals/deployment/windows.md
  mkdocs.yml_template
Labels: devops, documentation
