Repository Avaiga/taipy-doc, pull requests merged in 2023-12, with the labels that each got.

#746 Fix link for Background Remover
  mkdocs.yml_template
Labels: 📄 Documentation, 💥Malfunction

#751 Fix broken links in tutorials
  docs/knowledge_base/tutorials/complete_application/step_01/step_01.md
  docs/knowledge_base/tutorials/complete_application/step_02/step_02.md
  docs/knowledge_base/tutorials/complete_application/step_03/step_03.md
  docs/knowledge_base/tutorials/complete_application/step_04/step_04.md
  docs/knowledge_base/tutorials/complete_application/step_05/step_05.md
  docs/knowledge_base/tutorials/understanding_gui/step_01/step_01.md
  docs/knowledge_base/tutorials/understanding_gui/step_02/step_02.md
  docs/knowledge_base/tutorials/understanding_gui/step_03/step_03.md
  docs/knowledge_base/tutorials/understanding_gui/step_04/step_04.md
  docs/knowledge_base/tutorials/understanding_gui/step_05/step_05.md
  docs/knowledge_base/tutorials/understanding_gui/step_06/step_06.md
  docs/knowledge_base/tutorials/understanding_gui/step_07/step_07.md
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#757 Modify doc generation after repositories merge
  .gitignore
  Pipfile
  docs/contributing/contributing.md
  docs/manuals/gui/extension_assets.md
  docs/manuals/gui/extension_data.md
  docs/manuals/gui/extension_list_of_values.md
  docs/manuals/gui/extension_packaging.md
  docs/manuals/gui/viselements/controls.md_template
  tools/_setup_generation/step_gui_ext_refman.py
  tools/fetch_source_files.py
  tools/postprocess.py
Labels: 🖧 Devops, 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#754 Redirects homepage links to main tutorials
  docs/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#758 Adds a Credit Card Fraud Detection demo
  docs/knowledge_base/demos/fraud_detection.md
  docs/knowledge_base/demos/images/fraud_explanation.png
  docs/knowledge_base/demos/images/fraud_threshold.png
  docs/knowledge_base/demos/images/fraud_transactions.png
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#753 Fix broken links in tutorials
  docs/knowledge_base/tutorials/complete_application/step_01/step_01.md
  docs/knowledge_base/tutorials/complete_application/step_02/step_02.md
  docs/knowledge_base/tutorials/complete_application/step_03/step_03.md
  docs/knowledge_base/tutorials/complete_application/step_04/step_04.md
  docs/knowledge_base/tutorials/complete_application/step_05/step_05.md
  docs/knowledge_base/tutorials/understanding_gui/step_01/step_01.md
  docs/knowledge_base/tutorials/understanding_gui/step_02/step_02.md
  docs/knowledge_base/tutorials/understanding_gui/step_03/step_03.md
  docs/knowledge_base/tutorials/understanding_gui/step_04/step_04.md
  docs/knowledge_base/tutorials/understanding_gui/step_05/step_05.md
  docs/knowledge_base/tutorials/understanding_gui/step_06/step_06.md
  docs/knowledge_base/tutorials/understanding_gui/step_07/step_07.md
Labels: 📄 Documentation, 💥Malfunction

#756 Adds an LLM ChatBot tutorial and demo
  docs/knowledge_base/demos/chatbot.md
  docs/knowledge_base/demos/images/chatbot_meds_conv.png
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/index.md
  docs/knowledge_base/tutorials/chatbot/chatbot_cloud.png
  docs/knowledge_base/tutorials/chatbot/chatbot_env_var.png
  docs/knowledge_base/tutorials/chatbot/chatbot_first_result.png
  docs/knowledge_base/tutorials/chatbot/chatbot_plane.png
  docs/knowledge_base/tutorials/chatbot/chatbot_roundconv.png
  docs/knowledge_base/tutorials/chatbot/index.md
  docs/knowledge_base/tutorials/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High
