Repository Avaiga/taipy-doc, pull requests merged in 2023-10, with the labels that each got.

#586 Movie Genre Selector Demo
  docs/knowledge_base/demos/movie_genre_selector.md
  mkdocs.yml_template
Labels: 📄 Documentation

#584 COVID Dashboard Demo
  docs/knowledge_base/demos/covid_dashboard.md
  mkdocs.yml_template
Labels: 📄 Documentation

#585 Stock Visualization Demo
  docs/knowledge_base/demos/stock-visualization.md
  mkdocs.yml_template
Labels: 📄 Documentation

#587 Churn Classification Demo
  docs/knowledge_base/demos/churn_classification.md
  mkdocs.yml_template
Labels: 📄 Documentation

#600 Remove links explicitly pointing to a public version of the doc.
  docs/knowledge_base/tips/taipy_in_jupyter_notebooks.md
  docs/knowledge_base/tutorials/scenario_management_overview/step_01/step_01.md
Labels: 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium

#589 Bar Cutting Demo
  docs/knowledge_base/demos/bar_cutting.md
  mkdocs.yml_template
Labels: 📄 Documentation

#595 Fix/redesign regression
  taipy_theme/assets/stylesheets/avaiga.css
  taipy_theme/partials/header.html
  taipy_theme/partials/source.html
  taipy_theme/partials/tabs.html
  tools/partials/header.html
  tools/partials/source.html
  tools/partials/tabs.html
Labels: 📄 Documentation

#597 feat(style): style breadcrumbs
  taipy_theme/assets/stylesheets/avaiga.css
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#623 Properties of deeply inherited elements get lost
  tools/_setup_generation/step_viselements.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 💥Malfunction

#632 Update covid_dashboard.md
  docs/knowledge_base/demos/covid_dashboard.md
Labels: 📄 Documentation

#633 Update movie_genre_selector.md
  docs/knowledge_base/demos/movie_genre_selector.md
Labels: 📄 Documentation

#631 Update churn_classification.md
  docs/knowledge_base/demos/churn_classification.md
Labels: 📄 Documentation

#634 Update bar_cutting.md
  docs/knowledge_base/demos/bar_cutting.md
Labels: 📄 Documentation

#639 Update tweet_generation.md
  docs/knowledge_base/demos/tweet_generation.md
Labels: 📄 Documentation

#638 Update sentiment_analysis.md
  docs/knowledge_base/demos/sentiment_analysis.md
Labels: 📄 Documentation

#637 Update sales_dashboard.md
  docs/knowledge_base/demos/sales_dashboard.md
Labels: 📄 Documentation

#636 Update production_planning.md
  docs/knowledge_base/demos/production_planning.md
Labels: 📄 Documentation

#635 Predicting Stock Prices
  docs/knowledge_base/demos/stock_visualization.md
Labels: 📄 Documentation

#644 fix(header): Bring back dynamic site name and page title
  mkdocs.yml_template
  taipy_theme/.icons/taipy-logo-icon.svg
  taipy_theme/assets/stylesheets/avaiga.css
  taipy_theme/partials/header.html
Labels: 📄 Documentation

#648 Update Release Notes for GUI (unfinished!)
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/hidden.md
  docs/knowledge_base/index.md
  docs/knowledge_base/tips/jupyter_notebooks/index.md
  docs/knowledge_base/tutorials/scenario_management_overview/step_01/step_01.md
  docs/knowledge_base/tutorials/scenario_management_overview/step_04/index.md
  docs/knowledge_base/tutorials/scenario_management_overview/step_09/step_09.md
  docs/knowledge_base/tutorials/understanding_gui/step_01/step_01.md
  docs/manuals/auth/authorization.md
  docs/manuals/gui/binding.md
  docs/manuals/gui/callbacks.md
  docs/manuals/gui/configuration.md
  docs/manuals/gui/corelements/data_node.md_template
  docs/manuals/gui/corelements/data_node_selector.md_template
  docs/manuals/gui/corelements/job_selector.md_template
  docs/manuals/gui/corelements/scenario.md_template
  docs/manuals/gui/corelements/scenario_dag.md_template
  docs/manuals/gui/corelements/scenario_selector.md_template
  docs/manuals/gui/extension/dynamic_element/index.md
  docs/manuals/gui/extension/dynamic_element/scalar_props.md
  docs/manuals/gui/index.md
  docs/manuals/gui/notebooks.md
  docs/manuals/gui/notifications.md
  docs/manuals/gui/pages.md
  docs/manuals/gui/styling/index.md
  docs/manuals/gui/styling/stylekit.md
  docs/manuals/gui/viselements/blocks.md_template
  docs/manuals/gui/viselements/button.md_template
  docs/manuals/gui/viselements/chart.md_template
  docs/manuals/gui/viselements/controls.md_template
  docs/manuals/gui/viselements/date.md_template
  docs/manuals/gui/viselements/dialog.md_template
  docs/manuals/gui/viselements/expandable.md_template
  docs/manuals/gui/viselements/file_download.md_template
  docs/manuals/gui/viselements/file_selector.md_template
  docs/manuals/gui/viselements/image.md_template
  docs/manuals/gui/viselements/index.md
  docs/manuals/gui/viselements/indicator.md_template
  docs/manuals/gui/viselements/input.md_template
  docs/manuals/gui/viselements/layout.md_template
  docs/manuals/gui/viselements/menu.md_template
  docs/manuals/gui/viselements/navbar.md_template
  docs/manuals/gui/viselements/number.md_template
  docs/manuals/gui/viselements/pane.md_template
  docs/manuals/gui/viselements/part.md_template
  docs/manuals/gui/viselements/selector.md_template
  docs/manuals/gui/viselements/slider.md_template
  docs/manuals/gui/viselements/status.md_template
  docs/manuals/gui/viselements/table.md_template
  docs/manuals/gui/viselements/text.md_template
  docs/manuals/gui/viselements/toggle.md_template
  docs/manuals/gui/viselements/tree.md_template
  docs/migration.md
  docs/relnotes-legacy.md
  docs/relnotes.md
  mkdocs.yml_template
  tools/_setup_generation/step_refman.py
  tools/_setup_generation/step_viselements.py
  tools/postprocess.py
  tools/setup_generation.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 📈 Improvement, 🖰 GUI, 📄 Documentation

#656 Better navbar for the RefMan
  tools/_setup_generation/step_refman.py
  tools/postprocess.py
Labels: 🖧 Devops, 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#668 Page Builder API doc
  Pipfile
  docs/manuals/auth/authorization.md
  docs/manuals/gui/configuration.md
  docs/manuals/gui/corelements/scenario_selector.md_template
  docs/manuals/gui/index.md
  docs/manuals/gui/page_builder.md
  docs/manuals/gui/pages/index.md
  docs/manuals/gui/tgb-1-d.png
  docs/manuals/gui/tgb-1-l.png
  docs/manuals/gui/tgb-2-d.png
  docs/manuals/gui/tgb-2-l.png
  docs/manuals/gui/tgb-3-d.png
  docs/manuals/gui/tgb-3-l.png
  docs/manuals/gui/tgb-5-d.png
  docs/manuals/gui/tgb-5-l.png
  docs/manuals/gui/viselements/charts/others.md
  docs/manuals/gui/viselements/index.md
  docs/manuals/gui/viselements/slider.md_template
  docs/manuals/refmans/index.md
  docs/manuals/studio/gui.md
  docs/manuals/usermans/index.md
  docs/relnotes.md
  mkdocs.yml_template
  taipy_theme/assets/stylesheets/avaiga.css
  tools/_setup_generation/setup.py
  tools/_setup_generation/step_viselements.py
  tools/postprocess.py
Labels: 🟥 Priority: Critical, 🖰 GUI, 📄 Documentation, ✨New feature

#601 kb - tips - Long running Callbacks
  docs/knowledge_base/tips/long_callbacks/index.md
  docs/knowledge_base/tips/long_callbacks/long_running_callbacks.png
  mkdocs.yml_template
Labels: 📄 Documentation

#684 feat(knowledge-base): implement list filtering script
  Pipfile
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/index.md
  docs/knowledge_base/tips/index.md
  docs/knowledge_base/tutorials/index.md
  mkdocs.yml_template
  taipy_theme/assets/js/filter.js
  taipy_theme/assets/stylesheets/avaiga.css
Labels: 📄 Documentation

#696 Minor fixes
  docs/relnotes.md
  mkdocs.yml_template
Labels: 🖧 Devops, 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium
