Repository Avaiga/taipy-doc, pull requests merged in 2023-11, with the labels that each got.

#700 XRefs to RefMan improvements
  .gitignore
  docs/knowledge_base/tips/multipage_application/index.md
  docs/knowledge_base/tutorials/understanding_gui/index.md
  docs/knowledge_base/tutorials/understanding_gui/step_01/step_01.md
  docs/knowledge_base/tutorials/understanding_gui/step_02/step_02.md
  docs/knowledge_base/tutorials/understanding_gui/step_03/step_03.md
  docs/knowledge_base/tutorials/understanding_gui/step_04/step_04.md
  docs/knowledge_base/tutorials/understanding_gui/step_05/step_05.md
  docs/knowledge_base/tutorials/understanding_gui/step_06/step_06.md
  docs/knowledge_base/tutorials/understanding_gui/step_07/step_07.md
  docs/knowledge_base/tutorials/understanding_gui/tutorial.ipynb
  docs/manuals/auth/authentication.md
  docs/manuals/gui/configuration.md
  docs/manuals/gui/extension/dynamic_element/index.md
  docs/manuals/gui/extension/index.md
  docs/manuals/gui/extension/static_element.md
  docs/manuals/gui/index.md
  docs/manuals/gui/page_builder.md
  docs/manuals/gui/pages/index.md
  docs/manuals/gui/styling/index.md
  docs/manuals/run-deploy/deploy/azure.md
  docs/manuals/run-deploy/deploy/azure/index.md
  docs/manuals/run-deploy/deploy/databricks/index.md
  docs/manuals/run-deploy/deploy/heroku/index.md
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/linux/index.md
  docs/manuals/run-deploy/deploy/local/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  docs/manuals/run-deploy/deploy/windows/index.md
  docs/manuals/run-deploy/index.md
  docs/manuals/run-deploy/run/index.md
  docs/relnotes.md
  mkdocs.yml_template
  taipy_theme/assets/stylesheets/avaiga.css
  tools/_setup_generation/step_refman.py
  tools/postprocess.py
Labels: 🖧 Devops, 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#699 feat(tips): call relevant images for tips
  docs/knowledge_base/tips/css_style_kit/style_kit.png
  docs/knowledge_base/tips/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#705 Wrong links and doc in Authentication userman
  docs/manuals/auth/authentication.md
Labels: 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium

#706 Authentication UserMan improvements
  docs/manuals/auth/authentication.md
Labels: 📄 Documentation, 💥Malfunction, 🟩 Priority: Low

#707 Wrong links and doc in Authentication userman
  docs/manuals/auth/authentication.md
Labels: 📄 Documentation, 💥Malfunction, 🟩 Priority: Low

#716 Update doc for Studio 2.0
  docs/manuals/studio/config/elements.md
  docs/manuals/studio/config/files.md
  docs/manuals/studio/config/graphview.md
  docs/manuals/studio/config/index.md
  docs/manuals/studio/config/textedition.md
  docs/manuals/studio/images/config-icon-add-pipeline.png
  docs/manuals/studio/images/config_graphview_1.gif
  docs/manuals/studio/images/config_graphview_2.gif
  docs/manuals/studio/images/config_graphview_3.gif
  docs/manuals/studio/images/config_graphview_4.gif
  docs/manuals/studio/images/config_init.gif
  docs/manuals/studio/images/config_overview.png
  docs/manuals/studio/images/config_panel.png
  docs/manuals/studio/index.md
  mkdocs.yml_template
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation, 👩‍💻Studio

#724 Rename and rephrase tip on iframes
  docs/knowledge_base/index.md
  docs/knowledge_base/tips/3rd_party_components/index.md
  docs/knowledge_base/tips/3rd_party_components/part_illustration.png
  docs/knowledge_base/tips/3rd_party_components/sankey_diagram.png
  docs/knowledge_base/tips/iframes/iframes_illustration.png
  docs/knowledge_base/tips/iframes/index.md
  docs/knowledge_base/tips/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#727 :memo: Rewrites the intro of the cycles tutorial for clarity purposes
  docs/knowledge_base/tutorials/cycles_scopes/data_node_selector.png
  docs/knowledge_base/tutorials/cycles_scopes/index.md
  docs/knowledge_base/tutorials/cycles_scopes/visual_elements.png
Labels: Core, 📈 Improvement, 📄 Documentation

#726 Merge changes of GS from dev to 3.0
  docs/getting_started/index.md
Labels: 📈 Improvement, 📄 Documentation, good first issue, 🟧 Priority: High

#728 :memo: Rewrites INSTALLATION.MD in a shorter and clearer form
  INSTALLATION.md
Labels: 📄 Documentation

#729 :tada: Adds a Realtime Pollution Dashboard Demo
  docs/knowledge_base/demos/images/pollution_dashboard.png
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/demos/pollution_sensors.md
  docs/knowledge_base/index.md
  docs/knowledge_base/tips/multithreading/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation

#732 Add Background Remover demo in Doc
  docs/knowledge_base/demos/background_remover.md
  docs/knowledge_base/demos/images/background-remover.png
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#735 Expand contributing for knowledge base
  CONTRIBUTING.md
Labels: 📄 Documentation, 💬 Discussion

#736 Add the State illustration illustration
  docs/getting_started/index.md
  docs/getting_started/state_illustration.png
Labels: 📈 Improvement, 📄 Documentation

#690 :tada: Adds Drift Detection Demo
  docs/knowledge_base/demos/drift_detection.md
  docs/knowledge_base/demos/images/drift-detection-distributions.png
  docs/knowledge_base/demos/images/drift-detection-pipeline.png
  docs/knowledge_base/demos/images/drift-detection-step-1.png
  docs/knowledge_base/demos/images/drift-detection-step-2.png
  docs/knowledge_base/demos/images/drift-detection-step-3.png
  docs/knowledge_base/demos/index.md
  docs/knowledge_base/index.md
  mkdocs.yml_template
Labels: 📄 Documentation
