Repository Avaiga/taipy-doc, pull requests merged in 2024-01, with the labels that each got.

#767 Fixes image and link to chatbot demo
  docs/knowledge_base/demos/index.md
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#750 3rd Party Components tip - From Sankey to Folium
  docs/knowledge_base/tips/3rd_party_components/example.py
  docs/knowledge_base/tips/3rd_party_components/folium_map.png
  docs/knowledge_base/tips/3rd_party_components/footprint.csv
  docs/knowledge_base/tips/3rd_party_components/index.md
  docs/knowledge_base/tips/3rd_party_components/sankey_diagram.png
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟩 Priority: Low

#772 Fixes Chatbot demo div in knowledge base
  docs/knowledge_base/index.md
Labels: 📄 Documentation, 💥Malfunction, 🟩 Priority: Low

#771 Removes src import in page_builder page
  docs/manuals/gui/page_builder.md
Labels: 📄 Documentation, 💥Malfunction, 🟩 Priority: Low

#774 Fix after taipy-auth repository was moved to taipy-enterprise
  Pipfile
  tools/_setup_generation/step_refman.py
  tools/fetch_source_files.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 📄 Documentation, 💥Malfunction

#773 Add TGB in GS
  docs/getting_started/hello_world_md.py
  docs/getting_started/hello_world_tgb.py
  docs/getting_started/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#778 Fix links in Page Builder API doc
  docs/knowledge_base/tutorials/chatbot/index.md
  docs/manuals/gui/viselements/chart.md_template
  docs/manuals/gui/viselements/charts/home.html_fragment
  docs/relnotes-legacy.md
  tools/_setup_generation/step_refman.py
  tools/_setup_generation/step_viselements.py
  tools/fetch_source_files.py
  tools/postprocess.py
Labels: 🖰 GUI, 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium

#770 Add databricks tip
  docs/knowledge_base/index.md
  docs/knowledge_base/tips/databricks/databricks.png
  docs/knowledge_base/tips/databricks/example.py
  docs/knowledge_base/tips/databricks/index.md
  docs/knowledge_base/tips/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟩 Priority: Low

#784 Complete doc for the date_range control
  docs/manuals/gui/viselements/date_range-d.png
  docs/manuals/gui/viselements/date_range-dh.png
  docs/manuals/gui/viselements/date_range-l.png
  docs/manuals/gui/viselements/date_range-labels-d.png
  docs/manuals/gui/viselements/date_range-labels-l.png
  docs/manuals/gui/viselements/date_range-lh.png
  docs/manuals/gui/viselements/date_range-simple-d.png
  docs/manuals/gui/viselements/date_range-simple-l.png
  docs/manuals/gui/viselements/date_range-with_time-d.png
  docs/manuals/gui/viselements/date_range-with_time-l.png
  docs/manuals/gui/viselements/date_range.md_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#782 Rephrase demos
  docs/knowledge_base/demos/background_remover.md
  docs/knowledge_base/demos/chatbot.md
  docs/knowledge_base/demos/drift_detection.md
  docs/knowledge_base/demos/fraud_detection.md
  docs/knowledge_base/demos/pollution_sensors.md
  docs/knowledge_base/demos/talk_to_taipy.md
  docs/knowledge_base/tutorials/chatbot/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#783 Use new API with content for 3rd party components
  docs/knowledge_base/tips/3rd_party_components/example.py
  docs/knowledge_base/tips/3rd_party_components/index.md
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟩 Priority: Low

#787 Delete duplicate of cards
  docs/knowledge_base/demos/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#788 Update big data tip
  docs/knowledge_base/tips/big_data_models/index.md
Labels: 📄 Documentation, 🟩 Priority: Low

#790 Build would fail if private repos are not accessible.
  .gitignore
  Pipfile
  tools/fetch_source_files.py
Labels: 🖧 Devops, 📄 Documentation

#797 Add Colab and Python version
  docs/getting_started/index.md
  docs/installation/index.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#798 Merge pull request #797 from Avaiga/doc/fix-installation-guide
  docs/getting_started/index.md
  docs/installation/index.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#799 Wrong link to download my_config.py file
  docs/manuals/core/entities/data-node-mgt.md
  docs/manuals/core/entities/orchestrating-and-job-execution.md
  docs/manuals/core/entities/scenario-creation.md
  docs/manuals/core/entities/scenario-cycle-mgt.md
  docs/manuals/core/entities/sequence-mgt.md
  docs/manuals/core/entities/task-mgt.md
Labels: 📄 Documentation

#800 Completes code snippets in scenario tutorial
  docs/knowledge_base/tutorials/scenario_management_overview/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#796 Adding articles PySpark and Decimator
  docs/knowledge_base/tips/big_data_models/index.md
  docs/knowledge_base/tips/databricks/databricks.png
  docs/knowledge_base/tips/databricks/index.md
  docs/knowledge_base/tips/decimator/images/front.png
  docs/knowledge_base/tips/decimator/images/initial_curve.png
  docs/knowledge_base/tips/decimator/images/lttb_100.png
  docs/knowledge_base/tips/decimator/images/lttb_500.png
  docs/knowledge_base/tips/decimator/images/minmax_100.png
  docs/knowledge_base/tips/decimator/images/minmax_500.png
  docs/knowledge_base/tips/decimator/images/ramer_douglas_100.png
  docs/knowledge_base/tips/decimator/images/ramer_douglas_500.png
  docs/knowledge_base/tips/decimator/index.md
  docs/knowledge_base/tips/pyspark/images/GUI.png
  docs/knowledge_base/tips/pyspark/images/app_DAG.png
  docs/knowledge_base/tips/pyspark/images/front.png
  docs/knowledge_base/tips/pyspark/images/spark_DAG.png
  docs/knowledge_base/tips/pyspark/images/table_csv.png
  docs/knowledge_base/tips/pyspark/index.md
  mkdocs.yml_template
Labels: Core, 🖰 GUI, 🟨 Priority: Medium, ❌ Blocked

#806 Add Discord social channel
  Pipfile
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High
