Repository Avaiga/taipy-doc, pull requests merged in 2024-07, with the labels that each got.

#1027 Fix - Update permissions for manage_stale_issues_prs action
  .github/workflows/manage-stale-issue-pr.yml
Labels: 🖧 Devops, 💥Malfunction

#984 Add fullwidth description to file_selector and file_download
  docs/manuals/gui/viselements/file_download.md_template
  docs/manuals/gui/viselements/file_selector.md_template
Labels: 📈 Improvement, 📄 Documentation, 🥶Waiting for contributor

#1032 Adds tgb approach to decimator tutorial
  docs/tutorials/large_data/3_decimator/index.md
Labels: 🖰 GUI, 📄 Documentation, 🟩 Priority: Low

#1029 Add RAG chatbot tutorial
  docs/tutorials/fundamentals/5_rag_chatbot/images/conv_partial.png
  docs/tutorials/fundamentals/5_rag_chatbot/images/rag_screen.png
  docs/tutorials/fundamentals/5_rag_chatbot/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#1025 Add commodity trading application
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/bar_cutting/index.md
  docs/gallery/finance/commodity_trading/images/commodity_trading.png
  docs/gallery/finance/commodity_trading/images/feature_accuracies.png
  docs/gallery/finance/commodity_trading/images/feature_contribution.png
  docs/gallery/finance/commodity_trading/images/health_indicators.png
  docs/gallery/finance/commodity_trading/images/market_forecast.png
  docs/gallery/finance/commodity_trading/images/model_explainability.png
  docs/gallery/finance/commodity_trading/images/waterfall_chart.png
  docs/gallery/finance/commodity_trading/images/waterfall_chart_annotated.png
  docs/gallery/finance/commodity_trading/images/waterfall_chart_coal_flow.png
  docs/gallery/finance/commodity_trading/index.md
  docs/gallery/finance/fraud_detection/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High, ❌ Blocked

#1038 Merge pull request #1025 from Avaiga/doc/#1024-add-commodity-trading-…
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/bar_cutting/index.md
  docs/gallery/finance/commodity_trading/images/commodity_trading.png
  docs/gallery/finance/commodity_trading/images/feature_accuracies.png
  docs/gallery/finance/commodity_trading/images/feature_contribution.png
  docs/gallery/finance/commodity_trading/images/health_indicators.png
  docs/gallery/finance/commodity_trading/images/market_forecast.png
  docs/gallery/finance/commodity_trading/images/model_explainability.png
  docs/gallery/finance/commodity_trading/images/waterfall_chart.png
  docs/gallery/finance/commodity_trading/images/waterfall_chart_annotated.png
  docs/gallery/finance/commodity_trading/images/waterfall_chart_coal_flow.png
  docs/gallery/finance/commodity_trading/index.md
  docs/gallery/finance/fraud_detection/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation

#1039 Fix breadcrumbs generation for charts
  Pipfile
  tools/postprocess.py
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1037 Refactor/taipy#1472 - Update create cli command
  docs/manuals/cli/create.md
  docs/release-notes/index.md
  docs/tutorials/fundamentals/3_complete_application/index.md
Labels: 📈 Improvement, 📝Release Notes

#979 Add Styling column section to the Table page
  docs/manuals/userman/gui/viselements/generic/table-columnstyle-d.png
  docs/manuals/userman/gui/viselements/generic/table-columnstyle-l.png
  docs/manuals/userman/gui/viselements/generic/table.md_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation

#1045 Makes some deployment pages only available on demand
  docs/manuals/run-deploy/deploy/azure/index.md
  docs/manuals/run-deploy/deploy/databricks/images/curl-app.png
  docs/manuals/run-deploy/deploy/databricks/images/databricks-clusters.png
  docs/manuals/run-deploy/deploy/databricks/images/databricks-shell.png
  docs/manuals/run-deploy/deploy/databricks/images/global-architecture.svg
  docs/manuals/run-deploy/deploy/databricks/images/running-taipy-application.png
  docs/manuals/run-deploy/deploy/databricks/images/technical-architecture.svg
  docs/manuals/run-deploy/deploy/databricks/index.md
  docs/manuals/run-deploy/deploy/heroku/docker.md
  docs/manuals/run-deploy/deploy/heroku/git.md
  docs/manuals/run-deploy/deploy/heroku/index.md
  docs/manuals/run-deploy/deploy/heroku/setup.md
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/images/logo_artwork.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud_2.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud_3.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_connection.png
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  docs/manuals/run-deploy/deploy/windows/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟨 Priority: Medium

#1044 Doc/#1495 - Add document for filtering scenarios with creation_time
  docs/manuals/userman/sdm/scenario/index.md
  docs/release-notes/index.md
Labels: Core, 📄 Documentation, ✨New feature, 📝Release Notes

#1049 Add examples and images to the text control's doc
  Pipfile
  docs/manuals/userman/gui/viselements/generic/text-format-d.png
  docs/manuals/userman/gui/viselements/generic/text-format-l.png
  docs/manuals/userman/gui/viselements/generic/text-md-d.png
  docs/manuals/userman/gui/viselements/generic/text-md-l.png
  docs/manuals/userman/gui/viselements/generic/text-pre-d.png
  docs/manuals/userman/gui/viselements/generic/text-pre-l.png
  docs/manuals/userman/gui/viselements/generic/text-simple-d.png
  docs/manuals/userman/gui/viselements/generic/text-simple-l.png
  docs/manuals/userman/gui/viselements/generic/text.md_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#1040 Remove SQL repository
  docs/manuals/cli/migrate-entities.md
  docs/manuals/userman/configuration/core-config.md
  docs/release-notes/index.md
Labels: Core, 📄 Documentation, ⚙️Configuration, 📝Release Notes

#1054 Fix token leak in the logs.
  tools/fetch_source_files.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 📄 Documentation, 🔒 Staff only

#1055 Fix token leak in the logs.
  tools/fetch_source_files.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 📄 Documentation, 💥Malfunction

#1052 Propagates deployment docs change to latest
  docs/manuals/run-deploy/deploy/azure/index.md
  docs/manuals/run-deploy/deploy/databricks/images/curl-app.png
  docs/manuals/run-deploy/deploy/databricks/images/databricks-clusters.png
  docs/manuals/run-deploy/deploy/databricks/images/databricks-shell.png
  docs/manuals/run-deploy/deploy/databricks/images/global-architecture.svg
  docs/manuals/run-deploy/deploy/databricks/images/running-taipy-application.png
  docs/manuals/run-deploy/deploy/databricks/images/technical-architecture.svg
  docs/manuals/run-deploy/deploy/databricks/index.md
  docs/manuals/run-deploy/deploy/heroku/docker.md
  docs/manuals/run-deploy/deploy/heroku/git.md
  docs/manuals/run-deploy/deploy/heroku/index.md
  docs/manuals/run-deploy/deploy/heroku/setup.md
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/images/logo_artwork.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud_2.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud_3.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_connection.png
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  docs/manuals/run-deploy/deploy/windows/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟨 Priority: Medium

#1057 Add Supply Chain demo
  docs/gallery/decision_support/2_supply_chain/images/admin_page.png
  docs/gallery/decision_support/2_supply_chain/images/comparison_page.png
  docs/gallery/decision_support/2_supply_chain/images/data_page.png
  docs/gallery/decision_support/2_supply_chain/images/scenario_creation.png
  docs/gallery/decision_support/2_supply_chain/images/scenario_results.png
  docs/gallery/decision_support/2_supply_chain/images/total_comparison_page.png
  docs/gallery/decision_support/2_supply_chain/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High, ✨New feature

#1061 Add supply chain 3 echelon
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/admin_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/comparison_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/data_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/scenario_creation_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/scenario_map.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/scenario_sankey.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/total_comparison_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/index.md
  docs/gallery/decision_support/3_supply_chain/images/admin_page.png
  docs/gallery/decision_support/3_supply_chain/images/comparison_page.png
  docs/gallery/decision_support/3_supply_chain/images/data_page.png
  docs/gallery/decision_support/3_supply_chain/images/scenario_creation.png
  docs/gallery/decision_support/3_supply_chain/images/scenario_results.png
  docs/gallery/decision_support/3_supply_chain/images/total_comparison_page.png
  docs/gallery/decision_support/3_supply_chain/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High, ✨New feature
