Repository Avaiga/taipy-doc, pull requests merged in 2024-03, with the labels that each got.

#851 Added sequence edition section in scenario control.
  docs/manuals/gui/corelements/scenario-init-d.png
  docs/manuals/gui/corelements/scenario-init-l.png
  docs/manuals/gui/corelements/scenario.md_template
  docs/manuals/gui/viselements/index.md
  docs/relnotes.md
  tools/_setup_generation/step_refman.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High, 📝Release Notes

#852 Update release notes
  docs/manuals/core/entities/data-node-mgt.md
  docs/relnotes.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#825 Update docker deployment
  docs/manuals/run-deploy/deploy/docker/development.md
  docs/manuals/run-deploy/deploy/docker/production.md
Labels: 🖧 Devops, 📄 Documentation

#854 New introduction and small fixes
  docs/tutorials/fundamentals/2_scenario_management_overview/index.md
  docs/tutorials/fundamentals/2_scenario_management_overview/src/scenario_management.py
  docs/tutorials/fundamentals/2_scenario_management_overview/src/scenario_management.zip
  docs/tutorials/fundamentals/2_scenario_management_overview/src/scenario_managemet_toml.py
Labels: Core, 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#855 Change name of configuration
  docs/tutorials/fundamentals/2_scenario_management_overview/index.md
  docs/tutorials/fundamentals/2_scenario_management_overview/src/scenario_management.py
  docs/tutorials/fundamentals/2_scenario_management_overview/src/scenario_management.zip
Labels: 📈 Improvement, 🟩 Priority: Low

#856 Added documentation for the login control
  docs/manuals/gui/viselements/login-d.png
  docs/manuals/gui/viselements/login-dh.png
  docs/manuals/gui/viselements/login-l.png
  docs/manuals/gui/viselements/login-lh.png
  docs/manuals/gui/viselements/login.md_template
  docs/relnotes.md
  tools/_setup_generation/step_gui_ext_refman.py
Labels: 🖰 GUI, 📄 Documentation, 🟧 Priority: High, ✨New feature

#859 Shorten descriptions
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/bar_cutting/index.md
  docs/gallery/decision_support/churn_classification/index.md
  docs/gallery/decision_support/drift_detection/index.md
  docs/gallery/finance/1_stock_visualization/index.md
  docs/gallery/llm/5_chatbot/index.md
  docs/gallery/visualization/2_covid_dashboard/index.md
  docs/tutorials/integration/2_colab_with_ngrok/index.md
  docs/tutorials/integration/3_jupyter_notebooks/index.md
  docs/tutorials/scenario_management/8_version_management/index.md
  docs/tutorials/visuals/4_long_callbacks/index.md
  docs/tutorials/visuals/6_css_style_kit/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#861 Update documentation on pages to better introduce the Page Builder API
  README.md
  docs/manuals/auth/authorization.md
  docs/manuals/auth/index.md
  docs/manuals/core/concepts/index.md
  docs/manuals/core/index.md
  docs/manuals/gui/binding.md
  docs/manuals/gui/index.md
  docs/manuals/gui/pages/builder.md
  docs/manuals/gui/pages/html.md
  docs/manuals/gui/pages/index.md
  docs/manuals/gui/pages/markdown.md
  docs/manuals/gui/pages/tgb-1-d.png
  docs/manuals/gui/pages/tgb-1-l.png
  docs/manuals/gui/pages/tgb-2-d.png
  docs/manuals/gui/pages/tgb-2-l.png
  docs/manuals/gui/pages/tgb-3-d.png
  docs/manuals/gui/pages/tgb-3-l.png
  docs/manuals/gui/pages/tgb-5-d.png
  docs/manuals/gui/pages/tgb-5-l.png
  docs/manuals/gui/viselements/chart.md_template
  docs/manuals/gui/viselements/index.md
  docs/manuals/gui/viselements/login.md_template
  docs/relnotes.md
  docs/tutorials/fundamentals/1_understanding_gui/step_01/step_01.md
  docs/tutorials/visuals/3_multipage_application/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#860 Add a Gallery section
  CONTRIBUTING.md
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#864 Delete index files and ad to .gitgnore
  .gitignore
  docs/gallery/decision_support/index.md
  docs/gallery/finance/index.md
  docs/gallery/llm/index.md
  docs/gallery/other/index.md
  docs/gallery/visualization/index.md
Labels: 📄 Documentation, 🟨 Priority: Medium

#865 Add documentation for part.content and content providers
  docs/manuals/gui/corelements/data_node-data-scalar-d.png
  docs/manuals/gui/corelements/data_node-data-scalar-l.png
  docs/manuals/gui/corelements/data_node-data-tabular-table-d.png
  docs/manuals/gui/corelements/data_node-data-tabular-table-l.png
  docs/manuals/gui/corelements/data_node-init-d.png
  docs/manuals/gui/corelements/data_node-init-l.png
  docs/manuals/gui/corelements/data_node-properties-d.png
  docs/manuals/gui/corelements/data_node-properties-l.png
  docs/manuals/gui/corelements/data_node.md_template
  docs/manuals/gui/viselements/part-content-custom-d.png
  docs/manuals/gui/viselements/part-content-custom-l.png
  docs/manuals/gui/viselements/part-content-custom2-d.png
  docs/manuals/gui/viselements/part-content-custom2-l.png
  docs/manuals/gui/viselements/part-content-custom3-d.png
  docs/manuals/gui/viselements/part-content-custom3-l.png
  docs/manuals/gui/viselements/part-content-matplotlib-d.png
  docs/manuals/gui/viselements/part-content-matplotlib-l.png
  docs/manuals/gui/viselements/part.md_template
  docs/relnotes.md
  docs/tutorials/index.md
Labels: 🖰 GUI, 📄 Documentation, 🟧 Priority: High, ✨New feature

#866 Note on toggle as switch
  docs/manuals/gui/viselements/toggle-lov-d.png
  docs/manuals/gui/viselements/toggle-lov-l.png
  docs/manuals/gui/viselements/toggle-switch-d.png
  docs/manuals/gui/viselements/toggle-switch-l.png
  docs/manuals/gui/viselements/toggle.md_template
  docs/relnotes.md
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#867 Documentation on table edition actions and enumerated columns.
  docs/manuals/gui/pages/markdown.md
  docs/manuals/gui/viselements/login-init-d.png
  docs/manuals/gui/viselements/login-init-l.png
  docs/manuals/gui/viselements/login.md_template
  docs/manuals/gui/viselements/table-add-icon-d.png
  docs/manuals/gui/viselements/table-add-icon-l.png
  docs/manuals/gui/viselements/table-delete-icon-confirm-d.png
  docs/manuals/gui/viselements/table-delete-icon-confirm-l.png
  docs/manuals/gui/viselements/table-delete-icon-d.png
  docs/manuals/gui/viselements/table-delete-icon-l.png
  docs/manuals/gui/viselements/table-edit-enum-d.png
  docs/manuals/gui/viselements/table-edit-enum-l.png
  docs/manuals/gui/viselements/table-edit-enum-menu-d.png
  docs/manuals/gui/viselements/table-edit-enum-menu-l.png
  docs/manuals/gui/viselements/table-edit-icon-d.png
  docs/manuals/gui/viselements/table-edit-icon-l.png
  docs/manuals/gui/viselements/table-edit-value-d.png
  docs/manuals/gui/viselements/table-edit-value-l.png
  docs/manuals/gui/viselements/table-enum-example-d.png
  docs/manuals/gui/viselements/table-enum-example-l.png
  docs/manuals/gui/viselements/table.md_template
  docs/relnotes.md
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#868 Index properties in Page Builder API
  docs/manuals/gui/pages/builder.md
  docs/manuals/gui/viselements/charts/line.md
  docs/manuals/gui/viselements/charts/scatter.md
  docs/manuals/gui/viselements/layout.md_template
  tools/_setup_generation/step_viselements.py
Labels: 🖧 Devops, 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#870 Upgrades chatbot pages from gpt3 to gpt4
  docs/gallery/llm/5_chatbot/index.md
  docs/tutorials/fundamentals/4_chatbot/index.md
Labels: 📈 Improvement, 📄 Documentation

#862 Adds Industry Agglomeration Demo
  docs/gallery/visualization/7_industry_agglom/images/map_image.png
  docs/gallery/visualization/7_industry_agglom/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#871 Document selector's mode property
  docs/manuals/gui/viselements/part.md_template
  docs/manuals/gui/viselements/selector-check-d.png
  docs/manuals/gui/viselements/selector-check-l.png
  docs/manuals/gui/viselements/selector-default-d.png
  docs/manuals/gui/viselements/selector-default-l.png
  docs/manuals/gui/viselements/selector-multiple-d.png
  docs/manuals/gui/viselements/selector-multiple-l.png
  docs/manuals/gui/viselements/selector-radio-d.png
  docs/manuals/gui/viselements/selector-radio-l.png
  docs/manuals/gui/viselements/selector.md_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#872 Introduce the Decimator class
  docs/manuals/gui/viselements/chart.md_template
  docs/relnotes-legacy.md
Labels: 🖰 GUI, 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium

#873 More details on HTML support in Taipy GUI
  CONTRIBUTING.md
  docs/manuals/gui/extension/static_element.md
  docs/manuals/gui/pages/html.md
  docs/manuals/refmans/index.md
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#874 Pushes Industry Agglomeration Demo to latest
  CONTRIBUTING.md
  docs/gallery/visualization/7_industry_agglom/images/map_image.png
  docs/gallery/visualization/7_industry_agglom/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#876 Fix - Update outdated nb_of_workers attribute
  docs/manuals/core/config/advanced-config.md
  docs/manuals/core/config/job-config.md
Labels: Core, ⚙️Configuration, 💥Malfunction

#877 Hotfix 3.1.1 - Update outdated nb_of_workers attribute
  docs/manuals/core/config/advanced-config.md
  docs/manuals/core/config/job-config.md
Labels: Core, 📄 Documentation, ⚙️Configuration, 💥Malfunction

#881 Fix TGB titles and create code for long_callbacks
  docs/getting_started/index.md
  docs/tutorials/fundamentals/1_understanding_gui/src/src.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_02.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_02_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_03.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_03_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_04.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_04_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_05.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_05_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_06.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_06_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_07.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_07_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/step_02/step_02.md
  docs/tutorials/fundamentals/1_understanding_gui/step_03/step_03.md
  docs/tutorials/fundamentals/1_understanding_gui/step_05/step_05.md
  docs/tutorials/fundamentals/1_understanding_gui/step_06/step_06.md
  docs/tutorials/fundamentals/1_understanding_gui/step_07/step_07.md
  docs/tutorials/visuals/4_long_callbacks/index.md
  docs/tutorials/visuals/4_long_callbacks/src/long_callbacks.py
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#884 Improves the long callback example for clarity
  docs/tutorials/visuals/4_long_callbacks/images/approx_pi.png
  docs/tutorials/visuals/4_long_callbacks/index.md
  docs/tutorials/visuals/4_long_callbacks/src/long_callbacks.py
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#887 FIxes step numbering in multithreading tutorial
  docs/tutorials/visuals/5_multithreading/index.md
Labels: 📄 Documentation, 💥Malfunction, 🟩 Priority: Low

#890 Feature/taipy#949 - Add the improvement of the CLI error log to the relnote
  docs/relnotes.md
Labels: Core
