Repository Avaiga/taipy-doc, pull requests merged in 2024-10, with the labels that each got.

#1143 Test for proper retrieval of Designer
  tools/_setup_generation/step_designer.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 💥Malfunction

#1146 Feature/refacto ref man
  .gitignore
  Pipfile
  docs/refmans/gui/viselements/generic/chart.md_template
  docs/refmans/gui/viselements/generic/input.md_template
  docs/refmans/gui/viselements/generic/number.md_template
  docs/refmans/reference/index.md
  docs/tutorials/articles/cycles_scopes/index.md
  docs/tutorials/articles/cycles_scopes/src/scope_and_cycle.py
  docs/tutorials/articles/cycles_scopes/src/scope_and_cycle_toml.py
  docs/tutorials/articles/ibm_watson_studio/src/example.py
  docs/tutorials/articles/jupyter_notebooks/index.md
  docs/tutorials/articles/scenario_subscription/index.md
  docs/tutorials/articles/scenario_subscription/src/scenario_subscription.py
  docs/tutorials/articles/skippable_tasks/index.md
  docs/tutorials/articles/the_data_nodes/index.md
  docs/tutorials/articles/understanding_gui/step_03/step_03.md
  docs/userman/gui/pages/builder.md
  docs/userman/gui/viselements/introduction.md
  docs/userman/scenario_features/data-integration/data-node-history.md
  mkdocs.yml_template
  taipy_theme/assets/stylesheets/avaiga.css
  tools/_setup_generation/refman/__init__.py
  tools/_setup_generation/refman/cleaner.py
  tools/_setup_generation/refman/config_handler.py
  tools/_setup_generation/refman/entry.py
  tools/_setup_generation/refman/generator.py
  tools/_setup_generation/refman/package.py
  tools/_setup_generation/refman/reader.py
  tools/_setup_generation/refman/xref_updater.py
  tools/_setup_generation/step_refman.py
  tools/_setup_generation/step_viselements.py
  tools/postprocess.py
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#1151 Complete Release notes
  docs/release-notes/index.md
Labels: Core, 🟥 Priority: Critical, 📄 Documentation

#1153 Documentation for advanced 'large datasets' example
  docs/refmans/gui/viselements/generic/chart.md_template
  docs/refmans/gui/viselements/generic/charts/advanced.md_template
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_average-d.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_average-l.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_decimation-d.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_decimation-l.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_decimation-zoom1-d.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_decimation-zoom1-l.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_decimation-zoom2-d.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_decimation-zoom2-l.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_none-d.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_none-l.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_subsampling-d.png
  docs/refmans/gui/viselements/generic/charts/advanced_large_datasets_subsampling-l.png
  docs/userman/gui/pages/builder.md
  tools/_setup_generation/step_viselements.py
  tools/postprocess.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟨 Priority: Medium

#1161 Fix dead link
  docs/tutorials/getting_started/index.md_template
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1162 Merge pull request #1161 from Avaiga/bug/#2021-dead-link
  docs/tutorials/getting_started/index.md_template
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1163 Small adjustements for 4.0 doc
  docs/release-notes/index.md
  docs/tutorials/articles/using_tables/index.md
  mkdocs.yml_template
  tools/fetch_source_files.py
  tools/postprocess.py
Labels: 🟥 Priority: Critical, 📄 Documentation, 💥Malfunction

#1165 Create a button to link a Page Builder class to its visual element doc
  taipy_theme/assets/images/element-doc-white.svg
  taipy_theme/assets/stylesheets/avaiga.css
  tools/_setup_generation/step_viselements.py
  tools/postprocess.py
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1167 Correct links for 'Release Notes' and 'Contributing' in nav bar
  docs/refmans/gui/viselements/generic/date_range.md_template
  docs/refmans/gui/viselements/generic/dialog.md_template
  taipy_theme/partials/header.html
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1168 Correct links for 'Release Notes' and 'Contributing' in nav bar
  docs/refmans/gui/viselements/generic/date_range.md_template
  docs/refmans/gui/viselements/generic/dialog.md_template
  taipy_theme/partials/header.html
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1171 Duplicates databricks article temporarily
  docs/tutorials/integration/4_databricks/images/compare_scenarios.png
  docs/tutorials/integration/4_databricks/images/databricks.png
  docs/tutorials/integration/4_databricks/images/databricks_job.png
  docs/tutorials/integration/4_databricks/images/databricks_validated.png
  docs/tutorials/integration/4_databricks/images/submit_scenario.png
  docs/tutorials/integration/4_databricks/index.md
Labels: 📄 Documentation, 🟧 Priority: High

#1172 Temporarily duplicates Databricks article for dead link issue
  docs/tutorials/integration/4_databricks/images/compare_scenarios.png
  docs/tutorials/integration/4_databricks/images/databricks.png
  docs/tutorials/integration/4_databricks/images/databricks_job.png
  docs/tutorials/integration/4_databricks/images/databricks_validated.png
  docs/tutorials/integration/4_databricks/images/submit_scenario.png
  docs/tutorials/integration/4_databricks/index.md
Labels: 📄 Documentation, 🟧 Priority: High

#1177 Rollbacks Databricks article duplication
  docs/tutorials/integration/4_databricks/images/compare_scenarios.png
  docs/tutorials/integration/4_databricks/images/databricks.png
  docs/tutorials/integration/4_databricks/images/databricks_job.png
  docs/tutorials/integration/4_databricks/images/databricks_validated.png
  docs/tutorials/integration/4_databricks/images/submit_scenario.png
  docs/tutorials/integration/4_databricks/index.md
Labels: 📄 Documentation, 🟨 Priority: Medium

#1175 Feature/#1170 factorize installation contributing doc
  .gitignore
  docs/contributing/code_of_conduct.md
  docs/contributing/code_of_conduct.md_template
  docs/contributing/index.md
  docs/contributing/index.md_template
  docs/tutorials/getting_started/installation.md
  docs/tutorials/getting_started/installation.md_template
  tools/_setup_generation/setup.py
  tools/_setup_generation/step_contributors.py
  tools/_setup_generation/step_file_injection.py
  tools/fetch_source_files.py
Labels: 📄 Documentation, 🟨 Priority: Medium

#1180 Added empty template doc for alert and time controls.
  docs/refmans/gui/viselements/generic/alert.md_template
  docs/refmans/gui/viselements/generic/time.md_template
Labels: 🟥 Priority: Critical, 🖰 GUI, 📄 Documentation, 💥Malfunction

#1179 Doc/#1166 updated new AWS S3 Object capabilities
  docs/userman/scenario_features/data-integration/code-example/data-node-config/data-node-config-aws-s3.py
  docs/userman/scenario_features/data-integration/data-node-config.md
Labels: Core, 📄 Documentation, 📝Release Notes, hacktoberfest - 100💎, hacktoberfest

#1154 updated robots.txt Non latest documentation fixes#1960
  docs/robots.txt
Labels: 🖧 Devops, 📄 Documentation, 🟧 Priority: High, 🥶Waiting for contributor, hacktoberfest - 200💎💎, hacktoberfest

#1186 Fix/#2113 jrm version
  Pipfile
  docs/userman/advanced_features/auth/authentication.md
  docs/userman/advanced_features/auth/authorization.md
  docs/userman/advanced_features/auth/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High

#1176 Fix/taipy#2113 - Update authentication examples
  Pipfile
  docs/userman/advanced_features/auth/authentication.md
  docs/userman/advanced_features/auth/authorization.md
  docs/userman/advanced_features/auth/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 💥Malfunction, ✨New feature

#1190 Fix typo in part.md_template (#1187)
  docs/refmans/gui/viselements/generic/part.md_template
Labels: 📄 Documentation, 🟨 Priority: Medium
