Repository Avaiga/taipy-doc, pull requests merged in 2024-05, with the labels that each got.

#932 Add functions to scenario tutorial and improve compare tutorial
  docs/tutorials/fundamentals/2_scenario_management_overview/index.md
  docs/tutorials/scenario_management/6_scenario_comparison/images/comparison.png
  docs/tutorials/scenario_management/6_scenario_comparison/images/config.svg
  docs/tutorials/scenario_management/6_scenario_comparison/index.md
  docs/tutorials/scenario_management/6_scenario_comparison/src/scenario_comparison.py
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#931 Doc/taipy#410 - Update export_scenario() and import_scenario() user manual
  docs/manuals/core/entities/scenario-cycle-mgt.md
  docs/relnotes.md
Labels: Core, 📄 Documentation, ✨New feature

#938 Make qsr demo available and improve tuto
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/comparison_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/data_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/forecast_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/home_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/scenario_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/index.md_template
  docs/gallery/index.md_template
  docs/tutorials/fundamentals/1_understanding_gui/step_01/step_01.md
  docs/tutorials/fundamentals/2_scenario_management_overview/index.md
  docs/tutorials/scenario_management/2_the_data_nodes/index.md
  docs/tutorials/scenario_management/6_scenario_comparison/images/comparison.png
  docs/tutorials/scenario_management/6_scenario_comparison/images/config.svg
  docs/tutorials/scenario_management/6_scenario_comparison/index.md
  docs/tutorials/scenario_management/6_scenario_comparison/src/scenario_comparison.py
  docs/tutorials/visuals/3_multipage_application/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#939 Relnotes/taipy#1198 - Fix DataNode.is_up_to_date error
  docs/relnotes.md
Labels: Core, 📝Release Notes

#918 fix: add warning about issue when downgrading taipy
  docs/relnotes.md
Labels: 🖧 Devops, 📄 Documentation, 💥Malfunction

#947 Fix/#895 - The ellipsis should link to manuals/usermans/
  docs/index.md
Labels: 📄 Documentation, 💥Malfunction

#945 Cannot build doc if no access is given on private repositories.
  tools/fetch_source_files.py
Labels: 🟥 Priority: Critical, 🖧 Devops, 💥Malfunction

#948 Hotfix3.1/#895 - The ellipsis should link to manuals/usermans/
  docs/index.md
Labels: 📄 Documentation, 💥Malfunction

#949 Hotfix3.0/#895 - The ellipsis should link to manuals/usermans/
  docs/index.md
Labels: 📄 Documentation, 💥Malfunction

#951 Fix TypeError in the browser console.
  taipy_theme/assets/js/filter.js
Labels: 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium

#952 Centered the video elements with tp-video class.
  docs/tutorials/fundamentals/2_scenario_management_overview/index.md
  docs/tutorials/scenario_management/2_the_data_nodes/index.md
  docs/tutorials/scenario_management/3_skippable_tasks/index.md
  taipy_theme/assets/stylesheets/avaiga.css
Labels: 📈 Improvement, 📄 Documentation

#954 Fix/#953 - Remove explicit index.md link in href
  docs/manuals/usermans/index.md
Labels: 📄 Documentation, 💥Malfunction

#937 Doc/enterprise#334 - Cluster mode documentation
  docs/manuals/core/config/job-config.md
Labels: 📄 Documentation, ✨New feature

#943 Feature/#913 - Add doc for sorting scenarios
  docs/manuals/core/entities/scenario-cycle-mgt.md
  docs/relnotes.md
Labels: Core, 📄 Documentation, ✨New feature

#964 Skeleton for new chat and metric controls
  docs/manuals/gui/viselements/charts/home.html_fragment
  docs/manuals/gui/viselements/chat.md_template
  docs/manuals/gui/viselements/metric.md_template
Labels: 🟥 Priority: Critical, 📄 Documentation, 💥Malfunction

#967 Fix most generation warnings and errors related to links
  docs/manuals/core/config/data-node-config.md
  docs/manuals/core/entities/data-node-mgt.md
  docs/manuals/gui/corelements/job_selector.md_template
  docs/manuals/gui/extension/dynamic_element/scalar_props.md
  docs/manuals/gui/styling/stylekit.md
  docs/manuals/gui/viselements/charts/basics.md_template
  docs/manuals/gui/viselements/pane.md_template
  docs/manuals/gui/viselements/tree.md_template
  docs/manuals/studio/config/index.md
  docs/manuals/studio/gui.md
  docs/relnotes-legacy.md
  docs/tutorials/fundamentals/1_understanding_gui/step_02/step_02.md
  docs/tutorials/integration/3_jupyter_notebooks/index.md
  docs/tutorials/visuals/3_multipage_application/index.md
  tools/_setup_generation/step_viselements.py
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#969 Feature/taipy#1270 - Auto stale inactive issues and PRs
  .github/workflows/manage-stale-issue-pr.yml
  CONTRIBUTING.md
Labels: 🖧 Devops, ✨New feature
