Repository Avaiga/taipy-doc, pull requests merged in 2024-02, with the labels that each got.

#762 Fixed default date behavior documentation
  docs/manuals/gui/viselements/date.md_template
Labels: 🖰 GUI, 📄 Documentation, 💥Malfunction, 🟩 Priority: Low

#828 Document chart's figure property
  Pipfile
  docs/manuals/gui/viselements/chart-advanced.icon.svg
  docs/manuals/gui/viselements/chart-basics-icon.svg
  docs/manuals/gui/viselements/chart.md_template
  docs/manuals/gui/viselements/charts/advanced-python-lib-d.png
  docs/manuals/gui/viselements/charts/advanced-python-lib-l.png
  docs/manuals/gui/viselements/charts/advanced.md_template
  docs/manuals/gui/viselements/login.md_template
  docs/relnotes-legacy.md
  docs/relnotes.md
  tools/_setup_generation/step_refman.py
  tools/_setup_generation/step_viselements.py
Labels: 🟥 Priority: Critical, 🖰 GUI, 📄 Documentation, ✨New feature

#832 Document the format property of the date and date_range controls.
  docs/manuals/gui/viselements/date-format-d.png
  docs/manuals/gui/viselements/date-format-l.png
  docs/manuals/gui/viselements/date-not_editable-d.png
  docs/manuals/gui/viselements/date-not_editable-l.png
  docs/manuals/gui/viselements/date-simple-d.png
  docs/manuals/gui/viselements/date-simple-l.png
  docs/manuals/gui/viselements/date-with_time-d.png
  docs/manuals/gui/viselements/date-with_time-l.png
  docs/manuals/gui/viselements/date.md_template
  docs/manuals/gui/viselements/date_range.md_template
Labels: 🖰 GUI, 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#829 Create Taipy Cloud deployment documentation
  docs/knowledge_base/tips/taipy_cloud_deploy/images/taipy_cloud_2.png
  docs/knowledge_base/tips/taipy_cloud_deploy/images/taipy_cloud_3.png
  docs/knowledge_base/tips/taipy_cloud_deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/images/logo_artwork.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud_2.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_cloud_3.png
  docs/manuals/run-deploy/deploy/taipy-cloud/images/taipy_connection.png
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  mkdocs.yml_template
Labels: 🖧 Devops, 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#846 Hightlight Python API in Tutos
  docs/tutorials/fundamentals/1_understanding_gui/index.md
  docs/tutorials/fundamentals/1_understanding_gui/src/src.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_01.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_02.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_02_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_03.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_03_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_04.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_04.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_04_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_05.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_05.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_05_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_06.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_06.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_06_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_07.py
  docs/tutorials/fundamentals/1_understanding_gui/src/step_07.zip
  docs/tutorials/fundamentals/1_understanding_gui/src/step_07_tgb.py
  docs/tutorials/fundamentals/1_understanding_gui/step_01/step_01.md
  docs/tutorials/fundamentals/1_understanding_gui/step_02/step_02.md
  docs/tutorials/fundamentals/1_understanding_gui/step_03/step_03.md
  docs/tutorials/fundamentals/1_understanding_gui/step_04/step_04.md
  docs/tutorials/fundamentals/1_understanding_gui/step_05/step_05.md
  docs/tutorials/fundamentals/1_understanding_gui/step_06/step_06.md
  docs/tutorials/fundamentals/1_understanding_gui/step_07/step_07.md
  docs/tutorials/fundamentals/3_complete_application/step_01/step_01.md
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#850 Order cards/items
  mkdocs.yml_template
  tools/_setup_generation/step_gallery.py
  tools/_setup_generation/step_tutorials.py
Labels: 📄 Documentation, 💥Malfunction, 🟨 Priority: Medium

#848 Input and output not compatible in 3.1
  docs/manuals/cli/manage-versions.md
  docs/manuals/core/config/code_example/task_cfg/task-config_simple.py
  docs/manuals/core/entities/orchestrating-and-job-execution.md
  docs/manuals/core/versioning/code_example/main.py
  docs/manuals/core/versioning/code_example/main_with_multiple_changes.py
  docs/manuals/core/versioning/code_example/main_with_small_change.py
  docs/manuals/core/versioning/experiment_mode.md
  docs/manuals/core/versioning/production_mode.md
  docs/tutorials/integration/4_databricks/index.md
  docs/tutorials/large_data/1_pyspark/index.md
  docs/tutorials/scenario_management/2_the_data_nodes/images/data_notes_2.svg
  docs/tutorials/scenario_management/2_the_data_nodes/index.md
  docs/tutorials/scenario_management/5_job_execution/images/config.svg
  docs/tutorials/scenario_management/5_job_execution/index.md
  docs/tutorials/scenario_management/5_job_execution/src/job_execution.py
  docs/tutorials/scenario_management/6_scenario_comparison/images/config.svg
  docs/tutorials/scenario_management/6_scenario_comparison/index.md
  docs/tutorials/scenario_management/6_scenario_comparison/src/scenario_comparison.py
  docs/tutorials/scenario_management/7_scenario_subscription/images/config.svg
  docs/tutorials/scenario_management/7_scenario_subscription/index.md
  docs/tutorials/scenario_management/7_scenario_subscription/src/scenario_subscription.py
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#844 Simplify GS with no scenarios
  docs/getting_started/hello_world_md.py
  docs/getting_started/hello_world_scenario.py
  docs/getting_started/hello_world_tgb.py
  docs/getting_started/images/dynamic_chart.gif
  docs/getting_started/images/hello_world.svg
  docs/getting_started/images/icon-tutorials.svg
  docs/getting_started/images/result.png
  docs/getting_started/images/scenario.svg
  docs/getting_started/images/state_illustration.png
  docs/getting_started/images/visualize.svg
  docs/getting_started/index.md
  docs/getting_started/result.png
  docs/getting_started/state_illustration.png
  docs/installation/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High
