Repository Avaiga/taipy-doc, pull requests merged in 2024-09, with the labels that each got.

#1047 feature/#416 documentation for core notification
  docs/manuals/userman/sdm/events/code-example/create-and-start-core-event-consumer.py
  docs/manuals/userman/sdm/events/code-example/external-api-call-notifier.py
  docs/manuals/userman/sdm/events/code-example/register-specific-topic-to-notifier.py
  docs/manuals/userman/sdm/events/code-example/user-changes-notifier.py
  docs/manuals/userman/sdm/events/events-description.md
  docs/manuals/userman/sdm/events/examples.md
  docs/manuals/userman/sdm/events/index.md
  docs/manuals/userman/sdm/events/understanding-notifier-register.md
Labels: Core, 🟧 Priority: High

#1112 Adds Databricks Partner Token to docs
  docs/tutorials/articles/databricks/images/databricks_validated.png
  docs/tutorials/articles/databricks/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#1122 Rework the full doc for the pane block
  Pipfile
  docs/contributing/index.md
  docs/refmans/gui/viselements/generic/image-d.png
  docs/refmans/gui/viselements/generic/image-dh.png
  docs/refmans/gui/viselements/generic/image-l.png
  docs/refmans/gui/viselements/generic/image-lh.png
  docs/refmans/gui/viselements/generic/navbar.md_template
  docs/refmans/gui/viselements/generic/pane-anchor-d.png
  docs/refmans/gui/viselements/generic/pane-anchor-l.png
  docs/refmans/gui/viselements/generic/pane-as-page-d.png
  docs/refmans/gui/viselements/generic/pane-as-page-l.png
  docs/refmans/gui/viselements/generic/pane-intro1-button-d.png
  docs/refmans/gui/viselements/generic/pane-intro1-button-l.png
  docs/refmans/gui/viselements/generic/pane-intro1-d.png
  docs/refmans/gui/viselements/generic/pane-intro1-l.png
  docs/refmans/gui/viselements/generic/pane-intro2-d.png
  docs/refmans/gui/viselements/generic/pane-intro2-l.png
  docs/refmans/gui/viselements/generic/pane-intro3-d.png
  docs/refmans/gui/viselements/generic/pane-intro3-l.png
  docs/refmans/gui/viselements/generic/pane-persistent1-d.png
  docs/refmans/gui/viselements/generic/pane-persistent1-l.png
  docs/refmans/gui/viselements/generic/pane-persistent2-d.png
  docs/refmans/gui/viselements/generic/pane-persistent2-l.png
  docs/refmans/gui/viselements/generic/pane-simple-d.png
  docs/refmans/gui/viselements/generic/pane-simple-l.png
  docs/refmans/gui/viselements/generic/pane-simple-opened-d.png
  docs/refmans/gui/viselements/generic/pane-simple-opened-l.png
  docs/refmans/gui/viselements/generic/pane-styling1-d.png
  docs/refmans/gui/viselements/generic/pane-styling1-l.png
  docs/refmans/gui/viselements/generic/pane-styling2-d.png
  docs/refmans/gui/viselements/generic/pane-styling2-l.png
  docs/refmans/gui/viselements/generic/pane.md_template
  docs/release-notes/index.md
  docs/userman/advanced_features/configuration/job-config.md
  mkdocs.yml_template
  taipy_theme/assets/stylesheets/avaiga.css
  taipy_theme/partials/header.html
  tools/_setup_generation/step_viselements.py
  tools/postprocess.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#1124 Add navigation for contributing and rel notes
  docs/contributing/index.md
  mkdocs.yml_template
  tools/_setup_generation/step_refman.py
Labels: 📄 Documentation

#1125 Adds new TalkToTaipy to gallery
  docs/gallery/articles/talk_to_taipy/images/screenshot.png
  docs/gallery/articles/talk_to_taipy/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟨 Priority: Medium, ✨New feature

#1126 Integrate Designer user manual from taipy-designer repository
  .gitignore
  docs/refmans/gui/viselements/generic/pane.md_template
  mkdocs.yml_template
  tools/_setup_generation/setup.py
  tools/_setup_generation/step_designer.py
  tools/_setup_generation/step_gallery.py
  tools/_setup_generation/step_refman.py
  tools/fetch_source_files.py
Labels: 🟥 Priority: Critical, 📄 Documentation, ✨New feature

#1129 Added doc to the progress control
  docs/refmans/gui/viselements/generic/pane.md_template
  docs/refmans/gui/viselements/generic/progress-d.png
  docs/refmans/gui/viselements/generic/progress-dh.png
  docs/refmans/gui/viselements/generic/progress-l.png
  docs/refmans/gui/viselements/generic/progress-lh.png
  docs/refmans/gui/viselements/generic/progress-linear-d.png
  docs/refmans/gui/viselements/generic/progress-linear-l.png
  docs/refmans/gui/viselements/generic/progress-simple-d.png
  docs/refmans/gui/viselements/generic/progress-simple-l.png
  docs/refmans/gui/viselements/generic/progress-styling-circular1-d.png
  docs/refmans/gui/viselements/generic/progress-styling-circular1-l.png
  docs/refmans/gui/viselements/generic/progress-styling-circular2-d.png
  docs/refmans/gui/viselements/generic/progress-styling-circular2-l.png
  docs/refmans/gui/viselements/generic/progress-styling-linear1-d.png
  docs/refmans/gui/viselements/generic/progress-styling-linear1-l.png
  docs/refmans/gui/viselements/generic/progress-styling-linear2-d.png
  docs/refmans/gui/viselements/generic/progress-styling-linear2-l.png
  docs/refmans/gui/viselements/generic/progress-styling-texts1-d.png
  docs/refmans/gui/viselements/generic/progress-styling-texts1-l.png
  docs/refmans/gui/viselements/generic/progress-styling-texts2-d.png
  docs/refmans/gui/viselements/generic/progress-styling-texts2-l.png
  docs/refmans/gui/viselements/generic/progress-texts-d.png
  docs/refmans/gui/viselements/generic/progress-texts-l.png
  docs/refmans/gui/viselements/generic/progress.md_template
  tools/_setup_generation/step_refman.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#1127 Doc/taipy#1748 - Stop supporting python 3.8
  docs/release-notes/index.md
  docs/tutorials/articles/complete_application/index.md
  docs/tutorials/articles/dataiku/index.md
  docs/tutorials/articles/understanding_gui/index.md
  docs/tutorials/articles/understanding_gui/src/step_05.py
  docs/tutorials/articles/understanding_gui/step_05/step_05.md
  docs/tutorials/getting_started/index.md_template
  docs/tutorials/getting_started/installation.md
  docs/userman/gui/extension/index.md
  docs/userman/index.md
  docs/userman/run-deploy/deploy/linux/redhat.md
  docs/userman/run-deploy/deploy/linux/ubuntu.md
Labels: 🖧 Devops

#1135 A small change in viselements, one giant leap for step_viselements
  tools/_setup_generation/step_viselements.py
Labels: 🖧 Devops, 🖰 GUI, 📄 Documentation

#1140 Doc/taipy#1704 - Timestamp properties for Job and Submission
  docs/release-notes/index.md
  docs/userman/scenario_features/sdm/job/index.md
  docs/userman/scenario_features/sdm/submission/index.md
Labels: Core, 📄 Documentation, 📝Release Notes
