Repository Avaiga/taipy-doc, pull requests merged in 2024-06, with the labels that each got.

#978 Adds Multi-User tutorial describing the use of add_shared_variable and broadcast
  docs/tutorials/visuals/7_multi_user/images/broadcasted_msg.png
  docs/tutorials/visuals/7_multi_user/images/chat_screenshot.png
  docs/tutorials/visuals/7_multi_user/images/shared_msg.png
  docs/tutorials/visuals/7_multi_user/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#976 Adds a demo: a chatbot that supports image inputs using GPT-4o
  docs/gallery/llm/7_vision_chatbot/images/gpt4o_screen.png
  docs/gallery/llm/7_vision_chatbot/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟨 Priority: Medium, ✨New feature

#980 Adds a RAG Chatbot demo to the Gallery
  docs/gallery/llm/8_rag_chatbot/images/rag_screen.png
  docs/gallery/llm/8_rag_chatbot/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#982 Changes Industry Demo Title
  docs/gallery/visualization/7_industry_agglom/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#985 Add support for hiding a property's doc
  tools/_setup_generation/step_viselements.py
Labels: 🖧 Devops, 🖰 GUI, 📄 Documentation

#987 Adds new LLM demos and multi-user tuto to LATEST
  docs/gallery/llm/7_vision_chatbot/images/gpt4o_screen.png
  docs/gallery/llm/7_vision_chatbot/index.md
  docs/gallery/llm/8_rag_chatbot/images/rag_screen.png
  docs/gallery/llm/8_rag_chatbot/index.md
  docs/tutorials/visuals/7_multi_user/images/broadcasted_msg.png
  docs/tutorials/visuals/7_multi_user/images/chat_screenshot.png
  docs/tutorials/visuals/7_multi_user/images/shared_msg.png
  docs/tutorials/visuals/7_multi_user/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High

#992 Add Partial tutorial
  docs/tutorials/visuals/4_partials/images/illustration.png
  docs/tutorials/visuals/4_partials/images/partials_dashboard.png
  docs/tutorials/visuals/4_partials/index.md
  docs/tutorials/visuals/4_partials/src/example.py
  docs/tutorials/visuals/4_partials/src/example_md.py
  mkdocs.yml_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟩 Priority: Low

#993 Merge pull request #992 from Avaiga/doc/add-partial-tuto
  docs/tutorials/visuals/4_partials/images/illustration.png
  docs/tutorials/visuals/4_partials/images/partials_dashboard.png
  docs/tutorials/visuals/4_partials/index.md
  docs/tutorials/visuals/4_partials/src/example.py
  docs/tutorials/visuals/4_partials/src/example_md.py
  mkdocs.yml_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟩 Priority: Low

#994 Initialize the doc file for the progress control
  docs/manuals/gui/viselements/progress.md_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#996 Add a section on triggering notifcation from heavy function
  docs/tutorials/visuals/4_long_callbacks/images/long_running_callbacks.png
  docs/tutorials/visuals/4_long_callbacks/index.md
  docs/tutorials/visuals/4_long_callbacks/src/trigger_update.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟩 Priority: Low

#983 Add Watson Integration
  docs/tutorials/integration/4_databricks/index.md
  docs/tutorials/integration/6_ibm_watson_studio/images/illustration_Waston.png
  docs/tutorials/integration/6_ibm_watson_studio/index.md
  docs/tutorials/integration/6_ibm_watson_studio/src/example.py
  mkdocs.yml_template
Labels: Core, 📄 Documentation, 🟨 Priority: Medium

#998 Refactor/#397 - Move export_scenario and import_scenario to enterprise
  docs/relnotes.md
Labels: Core, 📄 Documentation, 📝Release Notes

#1003 Document the formatting capabilities of the table control
  docs/manuals/gui/viselements/table-format1-d.png
  docs/manuals/gui/viselements/table-format1-l.png
  docs/manuals/gui/viselements/table-format2-d.png
  docs/manuals/gui/viselements/table-format2-l.png
  docs/manuals/gui/viselements/table-format3-d.png
  docs/manuals/gui/viselements/table-format3-l.png
  docs/manuals/gui/viselements/table-format4-d.png
  docs/manuals/gui/viselements/table-format4-l.png
  docs/manuals/gui/viselements/table-format5-d.png
  docs/manuals/gui/viselements/table-format5-l.png
  docs/manuals/gui/viselements/table-format6-d.png
  docs/manuals/gui/viselements/table-format6-l.png
  docs/manuals/gui/viselements/table-format7-d.png
  docs/manuals/gui/viselements/table-format7-l.png
  docs/manuals/gui/viselements/table-formatting-d.png
  docs/manuals/gui/viselements/table-formatting-l.png
  docs/manuals/gui/viselements/table.md_template
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟨 Priority: Medium

#1004 Relnotes/taipy#671 - Add entries for templates with git and auth
  docs/relnotes.md
Labels: 📝Release Notes

#1011 Fix format
  docs/tutorials/integration/4_databricks/index.md
  docs/tutorials/integration/6_ibm_watson_studio/index.md
Labels: 🟥 Priority: Critical, 📄 Documentation

#1015 Transfer some demos to Enterprise
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/bar_cutting/index.md
  docs/gallery/decision_support/churn_classification/index.md
  docs/gallery/decision_support/drift_detection/index.md
  docs/gallery/decision_support/index.md_template
  docs/gallery/finance/1_stock_visualization/index.md
  docs/gallery/finance/4_sales_dashboard/index.md
  docs/gallery/finance/fraud_detection/index.md
  docs/gallery/finance/index.md_template
  docs/gallery/index.md_template
  docs/gallery/llm/5_chatbot/index.md
  docs/gallery/llm/6_talk_to_taipy/index.md
  docs/gallery/llm/7_vision_chatbot/index.md
  docs/gallery/llm/8_rag_chatbot/index.md
  docs/gallery/llm/index.md_template
  docs/gallery/llm/sentiment_analysis/index.md
  docs/gallery/llm/tweet_generation/index.md
  docs/gallery/other/background_remover/index.md
  docs/gallery/other/face_recognition/index.md
  docs/gallery/other/index.md_template
  docs/gallery/other/movie_genre_selector/index.md
  docs/gallery/visualization/2_covid_dashboard/index.md
  docs/gallery/visualization/7_industry_agglom/index.md
  docs/gallery/visualization/image_classif/index.md
  docs/gallery/visualization/index.md_template
  docs/gallery/visualization/pollution_sensors/index.md
  tools/_setup_generation/items/item.py
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1016 Add demos to Enterprise
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/bar_cutting/index.md
  docs/gallery/decision_support/churn_classification/index.md
  docs/gallery/decision_support/drift_detection/index.md
  docs/gallery/decision_support/index.md_template
  docs/gallery/finance/1_stock_visualization/index.md
  docs/gallery/finance/4_sales_dashboard/index.md
  docs/gallery/finance/fraud_detection/index.md
  docs/gallery/finance/index.md_template
  docs/gallery/index.md_template
  docs/gallery/llm/5_chatbot/index.md
  docs/gallery/llm/6_talk_to_taipy/index.md
  docs/gallery/llm/7_vision_chatbot/index.md
  docs/gallery/llm/8_rag_chatbot/index.md
  docs/gallery/llm/index.md_template
  docs/gallery/llm/sentiment_analysis/index.md
  docs/gallery/llm/tweet_generation/index.md
  docs/gallery/other/background_remover/index.md
  docs/gallery/other/face_recognition/index.md
  docs/gallery/other/index.md_template
  docs/gallery/other/movie_genre_selector/index.md
  docs/gallery/visualization/2_covid_dashboard/index.md
  docs/gallery/visualization/7_industry_agglom/index.md
  docs/gallery/visualization/image_classif/index.md
  docs/gallery/visualization/index.md_template
  docs/gallery/visualization/pollution_sensors/index.md
  docs/tutorials/integration/4_databricks/index.md
  docs/tutorials/integration/6_ibm_watson_studio/index.md
  tools/_setup_generation/items/item.py
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1017 Merge pull request #1008 from Avaiga/doc/#404-close-databricks
  docs/tutorials/integration/4_databricks/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1022 Hack pipfile generation to force numpy <2.0.0
  Pipfile
  tools/fetch_source_files.py
Labels: 🖧 Devops, 📄 Documentation, dependencies
