Repository Avaiga/taipy-doc, pull requests merged in 2024-12, with the labels that each got.

#1224 Update fraud detection demo
  docs/gallery/articles/fraud_detection/images/analysis_page.png
  docs/gallery/articles/fraud_detection/images/fraud_explanation.png
  docs/gallery/articles/fraud_detection/images/fraud_threshold.png
  docs/gallery/articles/fraud_detection/images/fraud_transactions.png
  docs/gallery/articles/fraud_detection/images/login_page.png
  docs/gallery/articles/fraud_detection/images/threshold_page.png
  docs/gallery/articles/fraud_detection/images/transactions_page.png
  docs/gallery/articles/fraud_detection/images/user_page.png
  docs/gallery/articles/fraud_detection/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#1225 Merge pull request #1224 from Avaiga/doc/update-fraud-detection-demo
  docs/gallery/articles/fraud_detection/images/analysis_page.png
  docs/gallery/articles/fraud_detection/images/fraud_explanation.png
  docs/gallery/articles/fraud_detection/images/fraud_threshold.png
  docs/gallery/articles/fraud_detection/images/fraud_transactions.png
  docs/gallery/articles/fraud_detection/images/login_page.png
  docs/gallery/articles/fraud_detection/images/threshold_page.png
  docs/gallery/articles/fraud_detection/images/transactions_page.png
  docs/gallery/articles/fraud_detection/images/user_page.png
  docs/gallery/articles/fraud_detection/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium

#1230 Make Page Builder great again
  docs/refmans/gui/viselements/generic/charts/advanced.md_template
  docs/refmans/gui/viselements/generic/dialog.md_template
  docs/refmans/gui/viselements/generic/expandable.md_template
  docs/refmans/gui/viselements/generic/indicator.md_template
  docs/refmans/gui/viselements/generic/layout.md_template
  docs/refmans/gui/viselements/generic/pane.md_template
  docs/refmans/gui/viselements/generic/part.md_template
  docs/refmans/gui/viselements/generic/table.md_template
  docs/refmans/gui/viselements/generic/tree.md_template
  docs/tutorials/articles/3rd_party_components/index.md
  docs/tutorials/articles/chatbot/index.md
  docs/tutorials/articles/colab_with_ngrok/index.md
  docs/tutorials/articles/complete_application/step_01/step_01.md
  docs/tutorials/articles/cycles_scopes/index.md
  docs/tutorials/articles/dataiku/index.md
  docs/tutorials/articles/decimator/index.md
  docs/tutorials/articles/multi_user/index.md
  docs/tutorials/articles/pyspark/index.md
  docs/tutorials/articles/scenario_management_overview/index.md
  docs/tutorials/articles/scenario_subscription/index.md
  docs/tutorials/articles/scenarios/index.md
  docs/tutorials/articles/understanding_gui/step_02/step_02.md
  docs/tutorials/articles/understanding_gui/step_03/step_03.md
  docs/tutorials/articles/understanding_gui/step_04/step_04.md
  docs/tutorials/articles/understanding_gui/step_05/step_05.md
  docs/tutorials/articles/understanding_gui/step_06/step_06.md
  docs/tutorials/articles/understanding_gui/step_07/step_07.md
  docs/tutorials/getting_started/index.md_template
  docs/userman/gui/binding.md
  docs/userman/gui/extension/dynamic_element/index.md
  docs/userman/gui/extension/tabular_data.md
  docs/userman/gui/pages/dialog/index.md
  docs/userman/gui/pages/index.md
  docs/userman/gui/pages/navigate/index.md
  docs/userman/gui/pages/pane/index.md
  docs/userman/gui/pages/partial/index.md
  docs/userman/gui/styling/index.md
  docs/userman/gui/viselements/introduction.md
  tools/_setup_generation/step_viselements.py
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1229 Feature/taipy 2267 fixwindows linux paths
  docs/release-notes/index.md
Labels: Core, 📄 Documentation

#1221 Add start with templates section
  docs/tutorials/getting_started/index.md_template
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#1234 Replace todo in release notes by link to entra ID documentation
  docs/release-notes/index.md
Labels: 🟥 Priority: Critical, 📄 Documentation

#1237 Update Release Notes for Taipy 4.0.2
  docs/release-notes/index.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#1240 Release Notes update for 4.0.2
  docs/release-notes/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1241 Better explain the base_url Gui setting.
  docs/userman/advanced_features/configuration/gui-config.md
  docs/userman/gui/pages/index.md
Labels: 🖰 GUI, 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1239 Doc/enterprise#491 - Expose the SystemCredentials
  docs/release-notes/index.md
  docs/userman/advanced_features/auth/authorization.md
Labels: 📄 Documentation, ✨New feature, 📝Release Notes

#1238 Update Release Notes for Taipy 4.0.2
  docs/release-notes/index.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#1247 Makes enterprise banners consistent
  docs/userman/advanced_features/auth/authentication.md
  docs/userman/advanced_features/auth/authorization.md
  docs/userman/advanced_features/auth/index.md
  docs/userman/advanced_features/configuration/job-config.md
  docs/userman/advanced_features/scheduling/index.md
  docs/userman/advanced_features/versioning/index.md
  docs/userman/advanced_features/versioning/production_mode.md
  docs/userman/ecosystem/cli/manage-versions.md
  docs/userman/scenario_features/sdm/scenario/index.md
  tools/_setup_generation/setup.py
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High
