Repository Avaiga/taipy-doc, pull requests merged in 2024-08, with the labels that each got.

#1062 Make Supply Chain with 3 echelons public
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/admin_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/comparison_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/data_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/scenario_creation_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/scenario_map.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/scenario_sankey.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/images/total_comparison_page.png
  docs/gallery/decision_support/2_supply_chain_3_echelons/index.md
  docs/gallery/decision_support/3_supply_chain/images/admin_page.png
  docs/gallery/decision_support/3_supply_chain/images/comparison_page.png
  docs/gallery/decision_support/3_supply_chain/images/data_page.png
  docs/gallery/decision_support/3_supply_chain/images/scenario_creation.png
  docs/gallery/decision_support/3_supply_chain/images/scenario_results.png
  docs/gallery/decision_support/3_supply_chain/images/total_comparison_page.png
  docs/gallery/decision_support/3_supply_chain/index.md
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High, ✨New feature

#1070 Document the chat control
  docs/manuals/userman/auth/authentication.md
  docs/manuals/userman/gui/binding.md
  docs/manuals/userman/gui/styling/index.md
  docs/manuals/userman/gui/viselements/generic/chat-calculator-d.png
  docs/manuals/userman/gui/viselements/generic/chat-calculator-l.png
  docs/manuals/userman/gui/viselements/generic/chat-d.png
  docs/manuals/userman/gui/viselements/generic/chat-dh.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-1-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-1-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-2-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-2-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-3-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-3-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-4-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-a-4-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-b-1-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-b-1-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-b-2-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-b-2-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-b-3-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-b-3-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-c-1-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-discuss-c-1-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-register-a-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-register-a-l.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-register-b-d.png
  docs/manuals/userman/gui/viselements/generic/chat-discuss-register-b-l.png
  docs/manuals/userman/gui/viselements/generic/chat-l.png
  docs/manuals/userman/gui/viselements/generic/chat-lh.png
  docs/manuals/userman/gui/viselements/generic/chat.md_template
  docs/manuals/userman/gui/viselements/generic/table.md_template
  docs/manuals/userman/gui/viselements/index.md_template
  docs/release-notes/index.md
  docs/release-notes/legacy.md
  docs/tutorials/fundamentals/5_rag_chatbot/index.md
  tools/postprocess.py
Labels: 🖰 GUI, 📄 Documentation, 🟧 Priority: High, ✨New feature

#1077 Full documentation for the metric control
  docs/manuals/userman/gui/viselements/generic/chat.md_template
  docs/manuals/userman/gui/viselements/generic/metric-color_map-d.png
  docs/manuals/userman/gui/viselements/generic/metric-color_map-l.png
  docs/manuals/userman/gui/viselements/generic/metric-d.png
  docs/manuals/userman/gui/viselements/generic/metric-delta_color-d.png
  docs/manuals/userman/gui/viselements/generic/metric-delta_color-l.png
  docs/manuals/userman/gui/viselements/generic/metric-dh.png
  docs/manuals/userman/gui/viselements/generic/metric-formats-d.png
  docs/manuals/userman/gui/viselements/generic/metric-formats-l.png
  docs/manuals/userman/gui/viselements/generic/metric-hide-value-d.png
  docs/manuals/userman/gui/viselements/generic/metric-hide-value-l.png
  docs/manuals/userman/gui/viselements/generic/metric-l.png
  docs/manuals/userman/gui/viselements/generic/metric-layout-dl.png
  docs/manuals/userman/gui/viselements/generic/metric-lh.png
  docs/manuals/userman/gui/viselements/generic/metric-range-d.png
  docs/manuals/userman/gui/viselements/generic/metric-range-l.png
  docs/manuals/userman/gui/viselements/generic/metric-simple-d.png
  docs/manuals/userman/gui/viselements/generic/metric-simple-l.png
  docs/manuals/userman/gui/viselements/generic/metric-type-d.png
  docs/manuals/userman/gui/viselements/generic/metric-type-l.png
  docs/manuals/userman/gui/viselements/generic/metric.md_template
  docs/manuals/userman/gui/viselements/generic/table.md_template
  docs/release-notes/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1078 Create an obvious button to drive readers to examples code on GitHub
  taipy_theme/assets/images/github-mark-white.svg
  taipy_theme/assets/stylesheets/avaiga.css
  tools/postprocess.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟨 Priority: Medium

#1053 Propagates decimator tutorial tgb approach to latest
  docs/tutorials/large_data/3_decimator/index.md
Labels: 📄 Documentation, 🟩 Priority: Low, ❌ Blocked

#1072 Doc/Enterprise#431 - Move production version to enterprise
  docs/manuals/cli/manage-versions.md
  docs/manuals/userman/configuration/core-config.md
  docs/manuals/userman/versioning/experiment_mode.md
  docs/manuals/userman/versioning/index.md
  docs/manuals/userman/versioning/production_mode.md
  docs/release-notes/index.md
Labels: Core, 📈 Improvement, 📄 Documentation, 📝Release Notes

#1097 Feature/#1086 - Revise scheduler doc
  docs/manuals/userman/scheduling/code-example/my_config.py
  docs/manuals/userman/scheduling/code-example/scheduler_example.py
  docs/manuals/userman/scheduling/index.md
Labels: Core

#1099 Fix/#1084 - Formatting issue with versioning page
  docs/manuals/userman/versioning/index.md
Labels: 💥Malfunction

#1096 Doc/taipy#1696 - Update Config.checker documentation
  docs/manuals/userman/configuration/config-checker.md
  docs/release-notes/index.md
Labels: Core, 📄 Documentation, ⚙️Configuration, ✨New feature

#1103 Makes Databricks docs public
  docs/tutorials/articles/databricks/images/compare_scenarios.png
  docs/tutorials/articles/databricks/images/databricks_job.png
  docs/tutorials/articles/databricks/images/submit_scenario.png
  docs/tutorials/articles/databricks/index.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation

#1080 Put application in DSS section as last section and add TGB
  docs/tutorials/articles/dataiku/index.md
  docs/tutorials/articles/dataiku/src/metrics_visualization_tgb.py
  docs/tutorials/articles/dataiku/src/scenario_dataiku_tgb.py
Labels: 📄 Documentation, 🟩 Priority: Low, 🥶Waiting for contributor

#1106 Makes Databricks tutorial public in latest
  docs/tutorials/integration/4_databricks/images/compare_scenarios.png
  docs/tutorials/integration/4_databricks/images/databricks_job.png
  docs/tutorials/integration/4_databricks/images/submit_scenario.png
  docs/tutorials/integration/4_databricks/index.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation
