Repository Avaiga/taipy-doc, pull requests merged in 2024-04, with the labels that each got.

#894 Merge pull request #893 from Sven-Bo/patch-2
  docs/tutorials/fundamentals/1_understanding_gui/step_07/step_07.md
Labels: 💥Malfunction, 🟨 Priority: Medium

#900 Remove all Taipy Cloud references
  Pipfile
  docs/getting_started/index.md
  docs/installation.md
  docs/manuals/cli/version.md
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  docs/manuals/run-deploy/index.md
  docs/tutorials/fundamentals/3_complete_application/index.md
  docs/tutorials/fundamentals/4_chatbot/index.md
  docs/tutorials/integration/index.md_template
  docs/tutorials/large_data/index.md_template
  docs/tutorials/scenario_management/index.md_template
  docs/tutorials/visuals/index.md_template
  mkdocs.yml_template
Labels: 📄 Documentation

#901 Taipy cloud reference removal from 3.1 version
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  docs/manuals/run-deploy/index.md
  docs/tutorials/fundamentals/4_chatbot/index.md
  docs/tutorials/integration/index.md_template
  docs/tutorials/large_data/index.md_template
  docs/tutorials/scenario_management/index.md_template
  docs/tutorials/visuals/index.md_template
  mkdocs.yml_template
Labels: 📄 Documentation

#902 Remove Taipy cloud references from 3.0
  docs/knowledge_base/index.md
  docs/knowledge_base/tips/index.md
  docs/knowledge_base/tips/taipy_cloud_deploy/index.md
  docs/knowledge_base/tutorials/chatbot/index.md
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud/index.md
  docs/manuals/run-deploy/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#903 Taipy Cloud reference removal from 2.4
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud.md
  docs/manuals/run-deploy/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#904 Taipy Cloud reference removal from 2.3
  docs/manuals/run-deploy/deploy/index.md
  docs/manuals/run-deploy/deploy/taipy-cloud.md
  docs/manuals/run-deploy/index.md
  mkdocs.yml_template
Labels: 📄 Documentation

#909 Update Release Notes for 3.1.1
  docs/relnotes.md
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#910 Update Release Notes for 3.1.1
  docs/relnotes.md
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#912 Add explicit robots.txt
  docs/robots.txt
Labels: 🖧 Devops, 📄 Documentation

#920 Removing 4 space convention
  mkdocs.yml_template
Labels: 📄 Documentation

#916 Add explicit robots.txt
  docs/robots.txt
Labels: 📄 Documentation, 🟧 Priority: High

#923 Add Application creation
  docs/tutorials/integration/5_dataiku/images/application_resfresh.png
  docs/tutorials/integration/5_dataiku/images/application_tab_image.png
  docs/tutorials/integration/5_dataiku/images/blocks.png
  docs/tutorials/integration/5_dataiku/images/code_studio.png
  docs/tutorials/integration/5_dataiku/images/dataiku.png
  docs/tutorials/integration/5_dataiku/images/definition.png
  docs/tutorials/integration/5_dataiku/images/metrics_visualization.png
  docs/tutorials/integration/5_dataiku/images/new_code_studio.png
  docs/tutorials/integration/5_dataiku/images/scenario_dataiku.png
  docs/tutorials/integration/5_dataiku/images/url_details_image.png
  docs/tutorials/integration/5_dataiku/index.md
  docs/tutorials/integration/5_dataiku/src/metrics_visualization.py
  docs/tutorials/integration/5_dataiku/src/scenario_dataiku.py
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High

#934 Taipy Designer doc build initialization
  tools/designer/.readthedocs.yaml
  tools/designer/requirements.txt
Labels: 🖧 Devops, 📄 Documentation

#933 Add QSR demo
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3a_qsr_sales_forecasting/images/comparison_page.png
  docs/gallery/decision_support/3a_qsr_sales_forecasting/images/data_page.png
  docs/gallery/decision_support/3a_qsr_sales_forecasting/images/forecast_page.png
  docs/gallery/decision_support/3a_qsr_sales_forecasting/images/home_page.png
  docs/gallery/decision_support/3a_qsr_sales_forecasting/images/scenario_page.png
  docs/gallery/decision_support/3a_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/index.md_template
  docs/gallery/index.md_template
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High

#936 Fix disclaimer
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/comparison_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/data_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/forecast_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/home_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/images/scenario_page.png
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, 🟧 Priority: High
