Repository Avaiga/taipy-doc, pull requests merged in 2025-01, with the labels that each got.

#1232 Revamping the "Understanding GUI" tutorial
  docs/tutorials/articles/sales_dashboard/images/final_app.png
  docs/tutorials/articles/sales_dashboard/images/thumbnail.png
  docs/tutorials/articles/sales_dashboard/images/yt-thumbnail.png
  docs/tutorials/articles/sales_dashboard/index.md
  docs/tutorials/articles/sales_dashboard/step_01/images/simple_app.png
  docs/tutorials/articles/sales_dashboard/step_01/step_01.md
  docs/tutorials/articles/sales_dashboard/step_02/images/filters.png
  docs/tutorials/articles/sales_dashboard/step_02/images/layout.png
  docs/tutorials/articles/sales_dashboard/step_02/images/styling_app.png
  docs/tutorials/articles/sales_dashboard/step_02/step_02.md
  docs/tutorials/articles/sales_dashboard/step_03/images/map.png
  docs/tutorials/articles/sales_dashboard/step_03/images/plotly_map.png
  docs/tutorials/articles/sales_dashboard/step_03/step_03.md
  docs/tutorials/articles/sales_dashboard/step_04/images/menu.png
  docs/tutorials/articles/sales_dashboard/step_04/step_04.md
  docs/tutorials/getting_started/index.md_template
  docs/tutorials/index.md_template
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟨 Priority: Medium, 🔒 Staff only

#1255 Publish new tutorial to release docs
  docs/index.md
  docs/tutorials/articles/sales_dashboard/images/final_app.png
  docs/tutorials/articles/sales_dashboard/images/thumbnail.png
  docs/tutorials/articles/sales_dashboard/images/yt-thumbnail.png
  docs/tutorials/articles/sales_dashboard/index.md
  docs/tutorials/articles/sales_dashboard/step_01/images/simple_app.png
  docs/tutorials/articles/sales_dashboard/step_01/step_01.md
  docs/tutorials/articles/sales_dashboard/step_02/images/filters.png
  docs/tutorials/articles/sales_dashboard/step_02/images/layout.png
  docs/tutorials/articles/sales_dashboard/step_02/images/styling_app.png
  docs/tutorials/articles/sales_dashboard/step_02/step_02.md
  docs/tutorials/articles/sales_dashboard/step_03/images/map.png
  docs/tutorials/articles/sales_dashboard/step_03/images/plotly_map.png
  docs/tutorials/articles/sales_dashboard/step_03/step_03.md
  docs/tutorials/articles/sales_dashboard/step_04/images/menu.png
  docs/tutorials/articles/sales_dashboard/step_04/step_04.md
  docs/tutorials/getting_started/index.md_template
  docs/tutorials/index.md_template
  mkdocs.yml_template
Labels: 📈 Improvement, 📄 Documentation, 🟧 Priority: High

#1260 Fix - Update dev Dockerfile example to optimize caching
  docs/userman/run-deploy/deploy/docker/development.md
Labels: 🖧 Devops, 📈 Improvement

#1264 Relnotes/taipy#2322 - Log error when sequence or scenario is inconsistent
  docs/release-notes/index.md
Labels: 📝Release Notes

#1268 Fix crossref resolution in function signature documentation
  tools/postprocess.py
Labels: 🖧 Devops, 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1269 Backport - Fix crossref resolution in function signature documentation
  tools/postprocess.py
Labels: 🖧 Devops, 📄 Documentation, 💥Malfunction, 🟧 Priority: High

#1270 Relnotes/taipy#2420 - Only check for core_version in not-development mode
  docs/release-notes/index.md
Labels: Core, 📈 Improvement, 💥Malfunction, 📝Release Notes
