Repository Avaiga/taipy-doc, pull requests merged in 2025-02, with the labels that each got.

#1273 Merge pull request #1262 from arcanaxion/add-user-management-tutorial
  Pipfile
  docs/tutorials/articles/user_management/images/admin_page_alice.png
  docs/tutorials/articles/user_management/images/admin_page_bob.png
  docs/tutorials/articles/user_management/images/alice_submits_scenario.png
  docs/tutorials/articles/user_management/images/bob_edits_company_name.png
  docs/tutorials/articles/user_management/images/company_page_alice.png
  docs/tutorials/articles/user_management/images/company_page_bob.png
  docs/tutorials/articles/user_management/images/header.png
  docs/tutorials/articles/user_management/images/login_page_guest.png
  docs/tutorials/articles/user_management/index.md
  mkdocs.yml_template
Labels: 📄 Documentation, ✨New feature

#1278 Description of Page Builder API generation for extension libraries.
  docs/refmans/gui/viselements/corelements/data_node_selector.md_template
  docs/userman/gui/extension/index.md
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High, 🔒 Staff only

#1279 Bug when processing unresolved cross-refs.
  docs/userman/gui/extension/chart.md
  mkdocs.yml_template
  tools/postprocess.py
Labels: 📄 Documentation, 💥Malfunction, 🟧 Priority: High, 🔒 Staff only
