Repository Avaiga/taipy-doc, pull requests merged in 2025-03, with the labels that each got.

#1287 Added doc and commented example for page modules
  docs/tutorials/articles/understanding_gui/step_03/step_03.md
  docs/tutorials/articles/using_tables/index.md
  docs/userman/advanced_features/configuration/gui-config.md
  docs/userman/gui/extension/chart.md
  docs/userman/gui/extension/index.md
  docs/userman/gui/notifications-d.png
  docs/userman/gui/notifications-l.png
  docs/userman/gui/notifications.md
  docs/userman/gui/pages/index.md
  docs/userman/gui/utilities.md
  mkdocs.yml_template
  tools/postprocess.py
Labels: 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#1291 Fix element cross-refs in all contexts
  docs/refmans/gui/viselements/generic/chart.md_template
  docs/userman/gui/extension/accessing_assets.md
  mkdocs.yml_template
  tools/_setup_generation/step_viselements.py
  tools/check_site.py
  tools/postprocess.py
Labels: 🖧 Devops, 📈 Improvement, 🖰 GUI, 📄 Documentation, 🟧 Priority: High

#1294 Explicit supported Python versions.
  docs/tutorials/articles/complete_application/index.md
  docs/tutorials/articles/sales_dashboard/index.md
  docs/tutorials/articles/understanding_gui/index.md
  docs/userman/gui/extension/index.md
  docs/userman/index.md
Labels: dependencies, python

#1263 Doc/#1209 - #1250 - Add documentation page for each application and page template
  docs/tp_templates/applications/default_app.md
  docs/tp_templates/applications/img/default_app_template_with_auth_dark.jpg
  docs/tp_templates/applications/img/default_app_template_with_auth_light.jpg
  docs/tp_templates/applications/img/sdm_app_template_with_job_dark.jpeg
  docs/tp_templates/applications/img/sdm_app_template_with_job_light.jpeg
  docs/tp_templates/applications/img/sdm_app_template_with_scenario_dark.jpeg
  docs/tp_templates/applications/img/sdm_app_template_with_scenario_light.jpeg
  docs/tp_templates/applications/sdm_app.md
  docs/tp_templates/img/visualize.svg
  docs/tp_templates/index.md
  docs/tp_templates/pages/data_management_page.md
  docs/tp_templates/pages/default_page.md
  docs/tp_templates/pages/img/dmp_template_dark.jpeg
  docs/tp_templates/pages/img/dmp_template_light.jpeg
  docs/tp_templates/pages/img/job_template_dark.jpeg
  docs/tp_templates/pages/img/job_template_light.jpeg
  docs/tp_templates/pages/img/login_template_dark.jpeg
  docs/tp_templates/pages/img/login_template_light.jpeg
  docs/tp_templates/pages/img/sdp_template_dark.jpeg
  docs/tp_templates/pages/img/sdp_template_light.jpeg
  docs/tp_templates/pages/job_management_page.md
  docs/tp_templates/pages/login_page.md
  docs/tp_templates/pages/root_page.md
  docs/tp_templates/pages/sdm_page.md
  docs/tutorials/articles/complete_application/index.md
  docs/userman/ecosystem/cli/create.md
  mkdocs.yml_template
  tools/postprocess.py
Labels: 📈 Improvement, 📄 Documentation, ✨New feature

#1299 Update Release Notes for 4.0.3
  docs/release-notes/index.md
  docs/tutorials/articles/complete_application/index.md
  docs/tutorials/articles/dataiku/index.md
  docs/tutorials/articles/sales_dashboard/index.md
  docs/tutorials/articles/understanding_gui/index.md
  docs/tutorials/getting_started/index.md_template
  docs/userman/gui/extension/index.md
  docs/userman/index.md
  docs/userman/operations/deploying/linux/ubuntu.md
Labels: 🟥 Priority: Critical, 📈 Improvement, 📄 Documentation
