Repository Avaiga/taipy-doc, pull requests merged in 2025-06, with the labels that each got.

#1327 Doc/#1315 - Document Azure blob data node
  docs/release-notes/4.2/index.md
  docs/userman/advanced_features/3rd-party-integration/azure.md
  docs/userman/advanced_features/3rd-party-integration/code-example/data-node-config-azure.py
  docs/userman/advanced_features/3rd-party-integration/code-example/data-node-config-file-based-with-azure-url.py
  docs/userman/scenario_features/data-integration/data-node-config.md
  mkdocs.yml_template
Labels: Core, 📄 Documentation, ✨New feature, 📝Release Notes, Enterprise

#1329 Update Release Notes for Taipy GUI 4.1
  docs/refmans/gui/viselements/generic/text-latex-d.png
  docs/refmans/gui/viselements/generic/text-latex-l.png
  docs/refmans/gui/viselements/generic/text.md_template
  docs/release-notes/3.0/index.md
  docs/release-notes/4.0/index.md
  docs/release-notes/4.1/index.md
  docs/release-notes/4.2/index.md
  docs/userman/gui/utilities.md
  tools/_setup_generation/refman/reader.py
  tools/_setup_generation/step_refman.py
Labels: 🟥 Priority: Critical, 📈 Improvement, 🖰 GUI, 📄 Documentation

#1330 Update Release Notes for Taipy GUI 4.1 (backport to release/4.1)
  docs/refmans/gui/viselements/generic/text-latex-d.png
  docs/refmans/gui/viselements/generic/text-latex-l.png
  docs/refmans/gui/viselements/generic/text.md_template
  docs/release-notes/3.0/index.md
  docs/release-notes/4.0/index.md
  docs/release-notes/4.1/index.md
  docs/tutorials/articles/understanding_gui/step_03/step_03.md
  docs/tutorials/articles/using_tables/index.md
  docs/userman/advanced_features/configuration/gui-config.md
  docs/userman/gui/notifications.md
  docs/userman/gui/utilities.md
  mkdocs.yml_template
  tools/_setup_generation/refman/reader.py
  tools/_setup_generation/step_refman.py
Labels: 🟥 Priority: Critical, 📈 Improvement, 🖰 GUI, 📄 Documentation

#1331 Fine tuning
  docs/release-notes/4.0/index.md
Labels: 📈 Improvement, 📄 Documentation, 🟩 Priority: Low

#1335 Fix doc generation warnings
  .gitignore
  docs/release-notes/2.1/index.md
  docs/release-notes/2.3/index.md
  docs/release-notes/3.0/index.md
  docs/release-notes/4.0/index.md
  docs/release-notes/4.1/index.md
  docs/release-notes/4.2/index.md
  docs/release-notes/index.md_template
  docs/tp_templates/applications/classification_app.md
  docs/tp_templates/applications/default_app.md
  docs/tp_templates/applications/sdm_app.md
  docs/userman/advanced_features/events/code-example/create-and-start-event-processor.py
  docs/userman/advanced_features/events/code-example/external-api-call-notifier.py
  docs/userman/advanced_features/events/code-example/register-to-advanced-topic.py
  docs/userman/advanced_features/events/code-example/register-to-predefined-topic.py
  docs/userman/advanced_features/events/code-example/register-to-specific-topic.py
  docs/userman/advanced_features/events/code-example/user-changes-notifier.py
  docs/userman/advanced_features/events/events-description.md
  docs/userman/advanced_features/events/examples.md
  docs/userman/advanced_features/events/index.md
  docs/userman/advanced_features/events/topics.md
  docs/userman/ecosystem/cli/create.md
  mkdocs.yml_template
  taipy_theme/partials/header.html
  tools/_setup_generation/setup.py
  tools/_setup_generation/step_release_notes_index.py
Labels: 🟨 Priority: Medium

#1338 Doc/remove demo links on 4.1
  CONTRIBUTING.md
  docs/gallery/articles/background_remover/index.md
  docs/gallery/articles/bar_cutting/index.md
  docs/gallery/articles/chatbot/index.md
  docs/gallery/articles/churn_classification/index.md
  docs/gallery/articles/commodity_trading/index.md
  docs/gallery/articles/covid_dashboard/index.md
  docs/gallery/articles/drift_detection/index.md
  docs/gallery/articles/face_recognition/index.md
  docs/gallery/articles/fraud_detection/index.md
  docs/gallery/articles/industry_agglom/index.md
  docs/gallery/articles/movie_genre_selector/index.md
  docs/gallery/articles/pollution_sensors/index.md
  docs/gallery/articles/production_planning/index.md
  docs/gallery/articles/qsr_sales_forecasting/index.md
  docs/gallery/articles/sales_dashboard/index.md
  docs/gallery/articles/sentiment_analysis/index.md
  docs/gallery/articles/stock_visualization/index.md
  docs/gallery/articles/supply_chain/index.md
  docs/gallery/articles/supply_chain_3_echelons/index.md
  docs/gallery/articles/supply_chain_monitoring/index.md
  docs/gallery/articles/talk_to_taipy/index.md
  docs/gallery/articles/tweet_generation/index.md
  docs/gallery/articles/vision_chatbot/index.md
  docs/tutorials/articles/chatbot/index.md
  docs/tutorials/articles/user_management/index.md
Labels: 📄 Documentation

#1340 remove links on 3.1
  CONTRIBUTING.md
  docs/gallery/decision_support/2_supply_chain_3_echelons/index.md
  docs/gallery/decision_support/3_production_planning/index.md
  docs/gallery/decision_support/3_qsr_sales_forecasting/index.md
  docs/gallery/decision_support/3_supply_chain/index.md
  docs/gallery/decision_support/bar_cutting/index.md
  docs/gallery/decision_support/churn_classification/index.md
  docs/gallery/decision_support/drift_detection/index.md
  docs/gallery/finance/1_stock_visualization/index.md
  docs/gallery/finance/4_sales_dashboard/index.md
  docs/gallery/finance/fraud_detection/index.md
  docs/gallery/llm/5_chatbot/index.md
  docs/gallery/llm/7_vision_chatbot/index.md
  docs/gallery/llm/sentiment_analysis/index.md
  docs/gallery/llm/tweet_generation/index.md
  docs/gallery/other/background_remover/index.md
  docs/gallery/other/face_recognition/index.md
  docs/gallery/other/movie_genre_selector/index.md
  docs/gallery/visualization/2_covid_dashboard/index.md
  docs/gallery/visualization/7_industry_agglom/index.md
  docs/gallery/visualization/pollution_sensors/index.md
  docs/tutorials/fundamentals/4_chatbot/index.md
Labels: 📄 Documentation
